In [1]:
import pandas as pd

# Replace '/path/to/your/FinanceClass.csv' with the actual path to your CSV file.
csv_file_path = '/Users/rossadams/Documents/Finances/ExportedCSVs/FinH12023CSV/Transactions-H1-Transactions.csv'

# Load your expenditure data from the CSV file into a Pandas DataFrame.
H1Transactions = pd.read_csv(csv_file_path)





# Get basic statistics about numerical columns in the DataFrame.
# print(data.describe())

# Check the unique values in a specific column (e.g., 'Description').
# print(data['Description'].unique())

# Check the number of rows and columns in the DataFrame.
# num_rows, num_columns = data.shape
# print(f"Number of Rows: {num_rows}, Number of Columns: {num_columns}")

In [1]:
import pandas as pd

# Replace '/path/to/your/FinanceClass.csv' with the actual path to your CSV file.
csv_file_path = '/Users/rossadams/Documents/Finances/ExportedCSVs/FinH12023CSV/Transactions-H1-Transactions.csv'

# Load your expenditure data from the CSV file into a Pandas DataFrame.
H1Transactions = pd.read_csv(csv_file_path)





# Get basic statistics about numerical columns in the DataFrame.
# print(data.describe())

# Check the unique values in a specific column (e.g., 'Description').
# print(data['Description'].unique())

# Check the number of rows and columns in the DataFrame.
# num_rows, num_columns = data.shape
# print(f"Number of Rows: {num_rows}, Number of Columns: {num_columns}")

In [5]:
# Inspect the first few rows of the DataFrame to understand the data structure.
print(H1Transactions.head())

         Date                              Description   Unnamed: 2  Amount  \
0  18/02/2023          *306-0043263-0976896 M UXBRIDGE  MRS J ADAMS    37.5
1  28/02/2023          *306-0043263-0976896 M UXBRIDGE  MRS J ADAMS   -22.5
2  20/02/2023          *306-0043291-4166692 M UXBRIDGE  MRS J ADAMS    22.5
3  30/03/2023          *306-0043919-5058005 M UXBRIDGE  MRS J ADAMS     7.0
4  18/04/2023  0100 - COLLIERSWOOD?    COLLIERS WOOD S  MRS J ADAMS    16.0

    Net  Unnamed: 5 Category  \
0 -37.5         NaN    Other
1  22.5         NaN    Other
2 -22.5         NaN    Other
3  -7.0         NaN    Other
4 -16.0         NaN    Other

                                          Unnamed: 7    Unnamed: 8 Unnamed: 9  \
0  RFI CHARGEBACK CLERK\nMARKS AND SPENCER\nALEXA...       SALFORD    M50 3SP
1  RFI CHARGEBACK CLERK\nMARKS AND SPENCER\nALEXA...       SALFORD    M50 3SP
2  RFI CHARGEBACK CLERK\nMARKS AND SPENCER\nALEXA...       SALFORD    M50 3SP
3  RFI CHARGEBACK CLERK\nMARKS AND SPENCER\nALEXA...       SALFORD    M50 3SP
4                              UNIT 1\nTANDEM CENTRE  COLLIERSWOOD         GU

                   Unnamed: 10              Unnamed: 11  \
0  UNITED KINGDOM OF GB AND NI  AT230490044000011820418
1  UNITED KINGDOM OF GB AND NI  AT230600045000011947084
2  UNITED KINGDOM OF GB AND NI  AT230520048000011666062
3  UNITED KINGDOM OF GB AND NI  AT230890038000011934194
4  UNITED KINGDOM OF GB AND NI  AT231090028000011841574

                           Unnamed: 12
0  General Purchases-Department Stores
1  General Purchases-Department Stores
2  General Purchases-Department Stores
3  General Purchases-Department Stores
4         General Purchases-Furnishing

In [6]:
# Get an overview of the DataFrame, including column names and data types.
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 786 entries, 0 to 785
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         786 non-null    object
 1   Description  786 non-null    object
 2   Unnamed: 2   444 non-null    object
 3   Amount       565 non-null    float64
 4   Net          786 non-null    float64
 5   Unnamed: 5   221 non-null    float64
 6   Category     786 non-null    object
 7   Unnamed: 7   438 non-null    object
 8   Unnamed: 8   408 non-null    object
 9   Unnamed: 9   438 non-null    object
 10  Unnamed: 10  438 non-null    object
 11  Unnamed: 11  444 non-null    object
 12  Unnamed: 12  438 non-null    object
dtypes: float64(3), object(10)
memory usage: 80.0+ KB
None

In [6]:
# Get basic statistics about numerical columns in the DataFrame.
print(H1Transactions.describe())

# Check the unique values in a specific column (e.g., 'Description').
print(H1Transactions['Description'].unique())

# Check the number of rows and columns in the DataFrame.
num_rows, num_columns = H1Transactions.shape
print(f"Number of Rows: {num_rows}, Number of Columns: {num_columns}")

             Amount           Net    Unnamed: 5
count  5.650000e+02    786.000000    221.000000
mean   1.038692e+07     -7.687481   4053.549729
std    2.399262e+07    886.861405   3329.893835
min   -3.124970e+03  -9000.000000   -100.410000
25%    6.990000e+00    -44.607500    921.360000
50%    2.000000e+01    -13.245000   3686.790000
75%    1.000000e+02     -6.037500   6640.840000
max    9.959370e+07  13291.950000  14397.700000
['*306-0043263-0976896 M UXBRIDGE' '*306-0043291-4166692 M UXBRIDGE'
 '*306-0043919-5058005 M UXBRIDGE'
 '0100 - COLLIERSWOOD?    COLLIERS WOOD S'
 '0800 HOMEFIX LTD        YATELEY' '0C385 BOOST             LONDON'
 '3CC5D                   LONDON'
 '3CPAYMENT*PRET A MANGER KINGSTON UPON T'
 '3CPAYMENT*STARBUCKS 127 LONDON' '3CPAYMENT*STARBUCKS 287 EDINBURGH'
 '3CPAYMENT*THE WOOLLEN M EDINBURGH' '3CPAYMENT*WELCOME BREAK HUNGERFORD'
 '3CPAYMENT*WELCOME BREAK POTTERS BAR' 'Absolute Taste Ltd t/a  Bicester'
 'ADAMS J     *FRS  REGULAR SAVER' 'ADAMS NF&N        From Ann For Easte'
 'ADAMS NF&N        Happy Anniversary' 'ADAMS NF&N        Happy Birthday'
 'ADAMS R     *FRS  REGULAR ROSS' 'ALDI COLLIERS WOOD 7810 COLLIERS WOOD'
 'AMAZON PRIME*1H35W84U4  AMZN.CO.UK/PM'
 'AMAZON PRIME*1Q63I9T84  AMZN.CO.UK/PM'
 'AMAZON PRIME*1R11Z9O64  AMZN.CO.UK/PM'
 'AMAZON PRIME*9Y70Z0TD5  AMZN.CO.UK/PM'
 'AMAZON PRIME*JM1BS6AB5  AMZN.CO.UK/PM'
 'AMAZON PRIME*K52KN36R5  AMZN.CO.UK/PM'
 'AMAZON PRIME*OY1E04205  AMZN.CO.UK/PM'
 'AMAZON PRIME*R68VU5OI5  AMZN.CO.UK/PM'
 'AMAZON PRIME*UX0IN94N5  AMZN.CO.UK/PM'
 'AMAZON.CO.UK*015J83AB5  AMAZON.CO.UK'
 'AMAZON.CO.UK*1A0AH7OW4  AMAZON.CO.UK'
 'AMAZON.CO.UK*1X8O02VO4  AMAZON.CO.UK'
 'AMAZON.CO.UK*HP1DE5MD5  AMAZON.CO.UK'
 'AMAZON.CO.UK*MT01N9865  AMAZON.CO.UK'
 'AMAZON.CO.UK*P87NW8EZ5  353-12477661' 'AMERICAN EXPRESS'
 'AMZ*BEST LEARNING UK    AMAZON.CO.UK'
 'AMZ*PARTY DELIGHTS L SV PAY.AMAZON.CO'
 'AMZNMKTPLACE            AMAZON.CO.UK' 'Angel Hill Site 62Farnborough'
 'APPLE.COM/BILL          HOLLYHILL'
 'APPLE.COM/BILL         08001076285   IE'
 'APPLE.COM/BILL         APPLE.COM/BIL IE                           '
 'APPLE.COM/BILL         CORK          IE                           '
 'APPLE.COM/UK            HOLLYHILL'
 'ARGOS LIMITED           MILTON KEYNES' 'Atom Easy         Atom Easy'
 'AVIOS GROUP Avios Group CRAWLEY'
 'B & Q 1076             NEW MALDEN    GB' 'B & Q 1076        NEW MALDEN'
 'B&Q NEW MALDEN 1076     NEW MALDEN' 'Babylon 76-78           London'
 'Babylon 76-78          London        GB'
 'BABYLON 76-78          LONDON  SW20  GB' 'Babylon 76-78     London'
 'BARCLAYS INSURANCE' 'BARCLAYS UK MTGES' 'Bayley and Sage   London'
 'Bayley Wimbledon       London        GB                           '
 'Bayley Wimbledon  London'
 'BB-TRAVEL INSURANC     GREAT DUNMOW  GB                           '
 "BLACKWELL'S EXETEREXETER" 'Booking.com             Amsterdam'
 'BOOTS                   BRISTOL' 'BOOTS                   NOTTINGHAM'
 'BOOTS 0853             WIMBLEDON     GB' 'BOOTS 1000        LONDON'
 'BOOTS OPTICIANS         LONDON' 'BOOTS REWARDSCHEME'
 'BOOTS THE CHEMIST       LONDON' 'BRISTOL AIRPORT SSP SAC BRISTOL'
 'BRITISH AIRWAYS GB DIRE WEST DRAYTON' 'BT GROUP PLC'
 'C1CA4 SPORTS            LONDON' 'CABVISION NETWORK LONDON'
 'CASH 0000    APR03SOUTH WEST T@13.53'
 'CASH 0000    JAN05SOUTH WEST T@11.44'
 'CASH 0000    JUN26SOUTH WEST T@09.48'
 'CASH Card    MAY05COOPERATIVE @16.05'
 'CASH Card    MAY07COOPERATIVE @12.22'
 'CASH Card    MAY09COOPERATIVE @09.57' 'CHARLOTTE TILBURY BTY   LONDON'
 'Chegworth Valley       Harrietsham   GB                           '
 'CHQ  IN AT 400704' 'CIRCOLO POPOLARE        LONDON'
 'CITY PANTRY             LONDON' 'CLEVEDON SF CONNECT     AVON'
 'CMCT CHURCH EVENTS      LONDON' 'CO-MISSION EVENTS       LONDON'
 'CO-OP GROUP 070789SHOREDITCH (S' 'CO-OP OLD STREET        LONDON'
 'CO-OP RAYNES PARK       LONDON' 'COSTA EDINBURGH AIRPORT EDINBURGH'
 'DART-CHARGE            LEEDS         GB                           '
 'DAVID LLOYD            LONDON        GB                           '
 'DAVID LLOYD LEISUR'
 'David Lloyd Leisure Li Hatfield      GB                           '
 'DAVID LLOYD LEISURE LIM HATFIELD' 'David Lloyd Raynes Park London'
 'DELIVEROO               LONDON' 'Dicky Birds       510066'
 'Dicky Birds       RORY  ADAMS' 'DISHOOM EDINBURGH       EDINBURGH'
 'DMN* PLONKGOLF-SHOREDI  COLCHESTER' 'DUNDONALD CHURCH  ADAMS'
 'EA5C9 BOOST             LONDON' 'EASYJET*EASYJET K4Q1CRP LUTON'
 'EASYJET*EASYJET K5B5WRS LUTON'
 'EDINBURGH TRAMS LIMITE EDINBURGH     GB                           '
 'EE LIMITED' 'EE LIMITED        FIRST PAYMENT'
 'ELYS                   LONDON        GB                           '
 'ELYS (WIMBLEDON) PLC    LONDON' 'EMMA BRIDGEWATER LTD    LONDON'
 'EPOSNOW*RASCALS SOFTPLA NORWICH' 'ESSO HOGS BACK SSTSURREY'
 'EXETER UNI PRINT REXETER' 'F9DDD SPORTS            LONDON'
 'FACULTY SCIENCE LIFACULTY SCIENC PAY' 'FACULTY SCIENCE LTNO REF'
 'FAMLY             FIRST PAYMENT' 'FE3FC BOOST             LONDON'
 'FINGAL                  LEITH EDINBUR' 'FIRST DIRECT VISA'
 'FIRST DIRECT VISA FIRST PAYMENT' 'FRANCO MANCA      LONDON'
 'Funding Circle UK' 'GOLFNOW                 BELFAST'
 'GOODWOOD ESTATE COMPANY CHICHESTER' 'Headmasters Wimbledon V London'
 'HM.COM                  LONDON' 'HMRC SA'
 'HOLLAND AND BARRETT     NUNEATON'
 'HOME RETAIL GROUP PLC   CENTRAL MILTON' 'HOMEOFFICE/PAYROLL'
 'IKEA LTD SHOP ONLINE   LONDON        GB                           '
 'JG *MACMILLAN CANCER S  LONDON' 'JOHN LEWIS DIRECT       LONDON'
 'JOHN LEWIS KINGSTON     KINGSTON UPON T'
 'JOJO MAMAN BEBE LTD-WIM WIMBLEDON' 'JOJO_ECOM_UK            NEWPORT'
 'Julia Adams       Money' 'Julia Adams       Playhouse'
 'JULIA MONZO       JULIA MONZO'
 'JUST PARKING LTD       LONDON        GB                           '
 'KENT PARKWOOD           CANTERBURY'
 'LA REDOUTE             BRADFORD WEST GB                           '
 'LAITHWAITES-RECURRING L READING'
 'LAKELAND.LIMITED       WINDERMERE    GB                           '
 'LARK                    LONDON'
 'LARK                   LONDON  SW20  GB' 'LB MERTON'
 'LB MERTON - RINGO PARK BASINGSTOKE   GB                           '
 'LIMPOPO BILTONG        MILTON KEYNES GB                           '
 'LOLA COFFEE             EDINBURGH'
 'LONDON BOROUGH OF      MERTON        GB                           '
 'LONDORA NAIL BOUTIQUE  WIMBLEDON     GB                           '
 'LTA Operations LimLondon' 'LUCAS CAR WASH LTD      LONDON'
 'M&S COLLIERS WOOD       LONDON' 'M&S WIMBLEDON           LONDON'
 'MARKS&SPENCER PLC SACA LONDON EC1V   GB'
 'MCDONALDS              WESTERHAM     GB                           '
 'MEDIPHARMACY           LONON         GB                           '
 'MILO S                 LONDON        GB                           '
 'MOBILE REBORN LTD 70-01-01-5496' 'Mum & Dad         NHM'
 'NEXT ONLINE NEXT APPLEP UNITED KINGDOM'
 'NO11                    EDINBURGH'
 'NYX*LRS                NewMalden     GB                           ' 'O2'
 'PAUL RAJKUMAR     DONATION' 'PAY* HANDY.COM-APR13   LONDON        GB'
 'PAY* HANDY.COM-JUN26   LONDON        GB'
 'PAY* HANDY.COM-MAY03   LONDON        GB'
 'PAY* HANDY.COM-MAY29   LONDON        GB' 'PAYMENT RECEIVED - THANK YOU'
 'PAYMENT RECEIVED - THANK YOU                                      '
 'PAYPAL *BMWORLDWIDE     01912705143'
 'PAYPAL *BODEN           4029357733'
 'PAYPAL *BQLIMITED       03330143357'
 'PAYPAL *CUTTERSQUID     02084530212' 'PAYPAL *MD UK           660494296'
 'PAYPAL *SCREWFIX        03330112112'
 'PAYPAL *TRG PLC         02031175455'
 'PAYPAL *XMASDIRECT      01350727555' 'PENNYHILL PARK SPABAGSHOT'
 'PHL & ELLAS KITCHEN     NEWTOWN'
 'Portland Scallop Compa Portland      GB                           '
 'Portland Scallop Compan Portland' 'POST OFFICE RAYNES PARK LONDON'
 'POSTMARK                LONDON'
 'POSTMARK TRADING LTD   LONDON        GB                           '
 'PRIME VIDEO *135OX6ZY4  353-12477661'
 'PRIME VIDEO *1O2VJ4UM4  353-12477661'
 'Provenance Village But London        GB                           '
 'PROVENANCE VILLAGE BUTC LONDON' 'Provenance VillageLondon'
 'Raynes Park ExpresLondon' 'Raynes Park Express     London'
 'Raynes Park Express    London        GB                           '
 'Rebecca Spence    Happy Birthday' 'RINGGO PARKING    MAIDSTONE'
 'ROBERT AND EDWARDS     LONDON  SW19  GB'
 'ROBERT AND EDWARDS LTD  LONDON' 'Ross Adams        IOU'
 'ROSS ADAMS        MONZO' 'Ross Adams        NowTV'
 'Ross Adams        Transfer' 'ROSS MONZO 2      MONZO TOP UP'
 "SAINSBURY'S LOCAL CLEVE CLEVEDON" "SAINSBURY'S LOCAL WESMI LONDON"
 "SAINSBURY'S SPRMRKTS LT LONDON" "SAINSBURY'S SUPERMARKET LONDON"
 'SAINSBURYS             RAYNES PARK   GB                           '
 'Sarah Crabtree    Picnic' 'SEPHORA UK              ST PETER'
 'SHELL ENERGY' 'SHELL PEPYS 427        LONDON SW20   GB'
 'SHELTER NAT CAMP' 'SHELTER NAT CAMP  FIRST PAYMENT'
 'SP BABY MORI LIMITED    LONDON' 'SP FRENCH CONNECTION    LONDON'
 'SP NEIGHBOURHOOD COF   LIVERPOOL     GB                           '
 'SP OMAZE UK             ALTRINCHAM'
 'SPAR                   LONDON        GB                           '
 'SPOTIFY           LONDON' 'SQ *AVIATOR HOTEL Farnborough'
 'SQ *FABULOUS COFFEE &  Whitstable    GB                           '
 'SQ *FORTITUDE COFFEE   Edinburgh     GB                           '
 'SQ *THE GREAT BIG EVEN Guildford     GB                           '
 'SQ *WIMBLEDON VILLAGE  London        GB                           '
 'STARBUCKS              LONDON        GB                           '
 'STARBUCKS BRS           BRISTOL'
 'SUMUP  *V & G ICE CREA SUTTON        GB                           '
 'SUMUP*DUNDONALD CHURCH  LONDON' 'T Archdale        Golf'
 'Tamesis Dock           London        GB                           '
 'TESCO PAY AT PUMP NEW MALDEN' 'TESCO PETROL 3883 3883T NEW MALDEN'
 'TESCO PFS 3883    NEW MALDEN' 'TESCO STORE 2934 2934TE NEW MALDEN'
 'TESCO STORE 5214 5214TE LONDON' 'TESCO STORE 6071 6071TE LONDON'
 'TESCO STORES 2288 CLEVEDON' 'TFL ENFORCEMENT OPS WEB LONDON'
 'TFL TRAVEL CH          TFL.GOV.UK/CP GB                           '
 'TFL TRAVEL CH     TFL.GOV.UK/CP' 'TFL TRAVEL CHARGE       TFL.GOV.UK/CP'
 'THAMES WATER' 'THE  WHITE  COMPANY THE UNITED KINGDOM'
 'THE CHAMPIONSHIPS, WIMB WIMBLEDON' 'THE CINNAMON TREE LTD   LONDON'
 'THE CONDE NAST PUBLICAT LONDON'
 'THE GOOD BOOK CO LTD   SURREY        GB                           '
 'THE GOOD BOOK COMPANY L Epsom' 'THE GOOD BOOK COMPANY L London'
 'THE IVY CAFE WIMBLEDON  LONDON' 'THE IVY ON THE SQUARE   EDINBURGH'
 'The Nelson Pharmacy     London' 'THE ROYAL YACHT BRITANN EDINBURGH'
 'THE ROYAL YACHT BRITANN LEITH' 'THE ROYAL YACHT BRITANN LEITH EDINBUR'
 'THE SCOTCH WHISKEY EXPE MIDLOTHIAN'
 'TM *TICKETMASTER        LOS ANGELES' 'TREATWELL               LONDON'
 'UBER TRIP               AMSTERDAM' 'UNIVERSITY OF EXETEXETER'
 'VANGUARD          LONDON' 'VANGUARD ASSET MANA06F02306050101352'
 'VANGUARD ASSET MANA06F02306050101353'
 'VANGUARD ASSET MANA06F02306050101355'
 'VANGUARD ASSET MANA06F02306050101356'
 'Vita Bella             Chelmsford    GB                           '
 'W H SMITH EUROPE TRAVEL BRISTOL' 'WAGAMAMA LIMITED        LONDON'
 'WAITROSE 0767 314N      POTTERS BAR'
 'WAITROSE 846           RAYNES PARK   GB'
 'WAITROSE RAYNES PARK    LONDON' 'WAITROSE WIMBLEDON      LONDON'
 'WEDGEWOOD               EDINBURGH'
 'Westminster Dental     London        GB                           '
 'WESTSIDE TENNIS CLUB    WIMBLEDON' 'WHITE HART HOTEL  EXETER'
 'WIMBLEDON BOOKS LTD     LONDON'
 'Wimbledon Flower Kiosk London        GB                           '
 'WINDMILL TEAROOMS      LONDON        GB                           '
 'WINDMILL TEAROOMS LONDON' 'Window Cleaner    16 Carlton Park Av'
 'WISHLIST                LONDON' 'WISLEY GLASSHOUSE CAFE  SURREY'
 'WM MORRISONS STORES     LONDON' 'WOLDINGHAM GOLF CLWOLDINGHAM CA'
 'WOODHAM MORTIMER GOLF  WOODHAM MORTI GB                           '
 'WORLD OF GOLF LONDON    NEW MALDEN'
 'WWW.ARGOS.CO.UK        MILTON KEYNES GB                           '
 'WWW.GOODEARTHGROUP.CO. LONDON  SW19  GB'
 'WWW.KIDLY.CO.UK        LONDON        GB                           '
 'WWW.PACTCOFFEE.COM      LONDON'
 'WWW.PPRUSSELLSQUARE.CO 02078333005   GB'
 'WWW.RAVECOFFEE.CO.UK   CIRENCESTERC  GB                           '
 'WWW.TAKEAWAY.JE        01534876163   GB'
 'X4139 SPORTS            LONDON'
 'ZETTLE_*CHANGO EMPANAD LONDON        GB                           '
 'Zettle_*PLONK GOLFlondon'
 'ZETTLE_*THE WILDS GROU BARNET        GB                           ']
Number of Rows: 786, Number of Columns: 13

In [2]:
import os
import openai

In [ ]:
import os

openai.api_key = os.getenv("OPENAI_API_KEY")

In [ ]:
# Python
__pycache__/
*.py[cod]
*$py.class

# Jupyter Notebook
.ipynb_checkpoints

# Environment variables
.env

# Virtual environment
venv/
env/
ENV/

# IDE-specific files
.vscode/
.idea/
*.swp
*.swo

# OS-specific files
.DS_Store
Thumbs.db

# Logs
*.log

# Compiled Python files
*.pyc

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# PyInstaller
*.manifest
*.spec

# Installer logs
pip-log.txt
pip-delete-this-directory.txt

# Unit test / coverage reports
htmlcov/
.tox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
.hypothesis/

# Translations
*.mo
*.pot

# Django stuff:
*.log
local_settings.py
db.sqlite3

# Flask stuff:
instance/
.webassets-cache

# Scrapy stuff:
.scrapy

# Sphinx documentation
docs/_build/

# PyBuilder
target/

# Jupyter Notebook
.ipynb_checkpoints

# IPython
profile_default/
ipython_config.py

# pyenv
.python-version

# Celery beat schedule file
celerybeat-schedule

# SageMath parsed files
*.sage.py

# Environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

# Spyder project settings
.spyderproject
.spyproject

# Rope project settings
.ropeproject

# mkdocs documentation
/site

# mypy
.mypy_cache/
.dmypy.json
dmypy.json

# Pyre type checker
.pyre/

# CSV files (uncomment if you want to ignore all CSV files)
# *.csv

# Specific files
FinanceClass.ipynb

In [4]:
openai.Model.list()

<OpenAIObject list at 0x7fc12d7d4220> JSON: {
  "object": "list",
  "data": [
    {
      "id": "text-search-babbage-doc-001",
      "object": "model",
      "created": 1651172509,
      "owned_by": "openai-dev"
    },
    {
      "id": "gpt-3.5-turbo-16k-0613",
      "object": "model",
      "created": 1685474247,
      "owned_by": "openai"
    },
    {
      "id": "curie-search-query",
      "object": "model",
      "created": 1651172509,
      "owned_by": "openai-dev"
    },
    {
      "id": "gpt-3.5-turbo-16k",
      "object": "model",
      "created": 1683758102,
      "owned_by": "openai-internal"
    },
    {
      "id": "text-search-babbage-query-001",
      "object": "model",
      "created": 1651172509,
      "owned_by": "openai-dev"
    },
    {
      "id": "babbage",
      "object": "model",
      "created": 1649358449,
      "owned_by": "openai"
    },
    {
      "id": "babbage-search-query",
      "object": "model",
      "created": 1651172509,
      "owned_by": "openai-dev"
    },
    {
      "id": "text-babbage-001",
      "object": "model",
      "created": 1649364043,
      "owned_by": "openai"
    },
    {
      "id": "whisper-1",
      "object": "model",
      "created": 1677532384,
      "owned_by": "openai-internal"
    },
    {
      "id": "text-similarity-davinci-001",
      "object": "model",
      "created": 1651172505,
      "owned_by": "openai-dev"
    },
    {
      "id": "davinci-similarity",
      "object": "model",
      "created": 1651172509,
      "owned_by": "openai-dev"
    },
    {
      "id": "code-davinci-edit-001",
      "object": "model",
      "created": 1649880484,
      "owned_by": "openai"
    },
    {
      "id": "curie-similarity",
      "object": "model",
      "created": 1651172510,
      "owned_by": "openai-dev"
    },
    {
      "id": "babbage-search-document",
      "object": "model",
      "created": 1651172510,
      "owned_by": "openai-dev"
    },
    {
      "id": "curie-instruct-beta",
      "object": "model",
      "created": 1649364042,
      "owned_by": "openai"
    },
    {
      "id": "text-search-ada-doc-001",
      "object": "model",
      "created": 1651172507,
      "owned_by": "openai-dev"
    },
    {
      "id": "davinci-instruct-beta",
      "object": "model",
      "created": 1649364042,
      "owned_by": "openai"
    },
    {
      "id": "text-similarity-babbage-001",
      "object": "model",
      "created": 1651172505,
      "owned_by": "openai-dev"
    },
    {
      "id": "text-search-davinci-doc-001",
      "object": "model",
      "created": 1651172505,
      "owned_by": "openai-dev"
    },
    {
      "id": "babbage-similarity",
      "object": "model",
      "created": 1651172505,
      "owned_by": "openai-dev"
    },
    {
      "id": "text-embedding-ada-002",
      "object": "model",
      "created": 1671217299,
      "owned_by": "openai-internal"
    },
    {
      "id": "davinci-search-query",
      "object": "model",
      "created": 1651172505,
      "owned_by": "openai-dev"
    },
    {
      "id": "text-similarity-curie-001",
      "object": "model",
      "created": 1651172507,
      "owned_by": "openai-dev"
    },
    {
      "id": "text-davinci-001",
      "object": "model",
      "created": 1649364042,
      "owned_by": "openai"
    },
    {
      "id": "text-search-davinci-query-001",
      "object": "model",
      "created": 1651172505,
      "owned_by": "openai-dev"
    },
    {
      "id": "ada-search-document",
      "object": "model",
      "created": 1651172507,
      "owned_by": "openai-dev"
    },
    {
      "id": "ada-code-search-code",
      "object": "model",
      "created": 1651172505,
      "owned_by": "openai-dev"
    },
    {
      "id": "babbage-002",
      "object": "model",
      "created": 1692634615,
      "owned_by": "system"
    },
    {
      "id": "davinci-002",
      "object": "model",
      "created": 1692634301,
      "owned_by": "system"
    },
    {
      "id": "davinci-search-document",
      "object": "model",
      "created": 1651172509,
      "owned_by": "openai-dev"
    },
    {
      "id": "curie-search-document",
      "object": "model",
      "created": 1651172508,
      "owned_by": "openai-dev"
    },
    {
      "id": "babbage-code-search-code",
      "object": "model",
      "created": 1651172509,
      "owned_by": "openai-dev"
    },
    {
      "id": "text-search-ada-query-001",
      "object": "model",
      "created": 1651172505,
      "owned_by": "openai-dev"
    },
    {
      "id": "code-search-ada-text-001",
      "object": "model",
      "created": 1651172507,
      "owned_by": "openai-dev"
    },
    {
      "id": "babbage-code-search-text",
      "object": "model",
      "created": 1651172509,
      "owned_by": "openai-dev"
    },
    {
      "id": "code-search-babbage-code-001",
      "object": "model",
      "created": 1651172507,
      "owned_by": "openai-dev"
    },
    {
      "id": "ada-search-query",
      "object": "model",
      "created": 1651172505,
      "owned_by": "openai-dev"
    },
    {
      "id": "ada-code-search-text",
      "object": "model",
      "created": 1651172510,
      "owned_by": "openai-dev"
    },
    {
      "id": "text-search-curie-query-001",
      "object": "model",
      "created": 1651172509,
      "owned_by": "openai-dev"
    },
    {
      "id": "text-davinci-002",
      "object": "model",
      "created": 1649880484,
      "owned_by": "openai"
    },
    {
      "id": "text-davinci-edit-001",
      "object": "model",
      "created": 1649809179,
      "owned_by": "openai"
    },
    {
      "id": "code-search-babbage-text-001",
      "object": "model",
      "created": 1651172507,
      "owned_by": "openai-dev"
    },
    {
      "id": "gpt-3.5-turbo",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "gpt-3.5-turbo-instruct-0914",
      "object": "model",
      "created": 1694122472,
      "owned_by": "system"
    },
    {
      "id": "ada",
      "object": "model",
      "created": 1649357491,
      "owned_by": "openai"
    },
    {
      "id": "text-ada-001",
      "object": "model",
      "created": 1649364042,
      "owned_by": "openai"
    },
    {
      "id": "ada-similarity",
      "object": "model",
      "created": 1651172507,
      "owned_by": "openai-dev"
    },
    {
      "id": "code-search-ada-code-001",
      "object": "model",
      "created": 1651172507,
      "owned_by": "openai-dev"
    },
    {
      "id": "text-similarity-ada-001",
      "object": "model",
      "created": 1651172505,
      "owned_by": "openai-dev"
    },
    {
      "id": "gpt-3.5-turbo-0301",
      "object": "model",
      "created": 1677649963,
      "owned_by": "openai"
    },
    {
      "id": "gpt-3.5-turbo-instruct",
      "object": "model",
      "created": 1692901427,
      "owned_by": "system"
    },
    {
      "id": "text-search-curie-doc-001",
      "object": "model",
      "created": 1651172509,
      "owned_by": "openai-dev"
    },
    {
      "id": "text-davinci-003",
      "object": "model",
      "created": 1669599635,
      "owned_by": "openai-internal"
    },
    {
      "id": "text-curie-001",
      "object": "model",
      "created": 1649364043,
      "owned_by": "openai"
    },
    {
      "id": "curie",
      "object": "model",
      "created": 1649359874,
      "owned_by": "openai"
    },
    {
      "id": "davinci",
      "object": "model",
      "created": 1649359874,
      "owned_by": "openai"
    },
    {
      "id": "dall-e-2",
      "object": "model",
      "created": 1698798177,
      "owned_by": "system"
    },
    {
      "id": "gpt-3.5-turbo-0613",
      "object": "model",
      "created": 1686587434,
      "owned_by": "openai"
    }
  ]
}

In [51]:
# import requests

# # Define your API key and endpoint
# # 
# endpoint = "https://api.openai.com/v1/completions"  # Use the appropriate endpoint for your API call

# # Define your prompt or input text
# # prompt = "Classify the following purchase description into one of the following categories in this list:(lunch, coffee, clothes, baby). The purchase descriptionis:('3CPAYMENT*STARBUCKS 127)"

# # Define the data for your API request
# data = {
#     "model": "gpt-3.5-turbo-instruct",
#     "prompt": prompt,
#     "max_tokens": 20,
#     "temperature": 0
# }

# # Set up the headers with your API key
# headers = {
#     "Authorization": f"Bearer {openai.api_key}",
#     "Content-Type": "application/json",
# }

# # Make the API request
# response = requests.post(endpoint, json=data, headers=headers)

# # Check for a successful response and process the output
# if response.status_code == 200:
#     result = response.json()
#     generated_text = result["choices"][0]["text"]
#     print(generated_text)
# else:
#     print(f"Error: {response.status_code} - {response.text}")

 GB


Other

In [8]:
prompt="Hello, how are you?"
data = {
    "model": "gpt-3.5-turbo-instruct",
    "prompt": prompt,
    "max_tokens": 20,
    "temperature": 0
}
# Make the API request
response = requests.post(endpoint, json=data, headers=headers)

In [9]:
print(headers)

{'Authorization': 'Bearer REMOVED', 'Content-Type': 'application/json'}

In [10]:
print(data)

{'model': 'gpt-3.5-turbo-instruct', 'prompt': 'Hello, how are you?', 'max_tokens': 20, 'temperature': 0}

In [11]:
print(json)

NameError: name 'json' is not defined

In [16]:
response = requests.post(endpoint, json=data, headers=headers)
if response.status_code == 200:
    result = response.json()
    print(result)
else:
    print(f"Error: {response.status_code} - {response.text}")

Error: 400 - {
  "error": {
    "message": "'messages' is a required property",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

In [42]:
print(data)

{'model': 'gpt-3.5-turbo-instruct', 'prompt': "Classify the following purchase description into one of the following categories in this list:(lunch, coffee, clothes, baby). The purchase descriptionis:('3CPAYMENT*STARBUCKS 127)", 'max_tokens': 20, 'temperature': 0}

In [24]:
print(H1Transactions['Description'].unique())

['*306-0043263-0976896 M UXBRIDGE' '*306-0043291-4166692 M UXBRIDGE'
 '*306-0043919-5058005 M UXBRIDGE'
 '0100 - COLLIERSWOOD?    COLLIERS WOOD S'
 '0800 HOMEFIX LTD        YATELEY' '0C385 BOOST             LONDON'
 '3CC5D                   LONDON'
 '3CPAYMENT*PRET A MANGER KINGSTON UPON T'
 '3CPAYMENT*STARBUCKS 127 LONDON' '3CPAYMENT*STARBUCKS 287 EDINBURGH'
 '3CPAYMENT*THE WOOLLEN M EDINBURGH' '3CPAYMENT*WELCOME BREAK HUNGERFORD'
 '3CPAYMENT*WELCOME BREAK POTTERS BAR' 'Absolute Taste Ltd t/a  Bicester'
 'ADAMS J     *FRS  REGULAR SAVER' 'ADAMS NF&N        From Ann For Easte'
 'ADAMS NF&N        Happy Anniversary' 'ADAMS NF&N        Happy Birthday'
 'ADAMS R     *FRS  REGULAR ROSS' 'ALDI COLLIERS WOOD 7810 COLLIERS WOOD'
 'AMAZON PRIME*1H35W84U4  AMZN.CO.UK/PM'
 'AMAZON PRIME*1Q63I9T84  AMZN.CO.UK/PM'
 'AMAZON PRIME*1R11Z9O64  AMZN.CO.UK/PM'
 'AMAZON PRIME*9Y70Z0TD5  AMZN.CO.UK/PM'
 'AMAZON PRIME*JM1BS6AB5  AMZN.CO.UK/PM'
 'AMAZON PRIME*K52KN36R5  AMZN.CO.UK/PM'
 'AMAZON PRIME*OY1E04205  AMZN.CO.UK/PM'
 'AMAZON PRIME*R68VU5OI5  AMZN.CO.UK/PM'
 'AMAZON PRIME*UX0IN94N5  AMZN.CO.UK/PM'
 'AMAZON.CO.UK*015J83AB5  AMAZON.CO.UK'
 'AMAZON.CO.UK*1A0AH7OW4  AMAZON.CO.UK'
 'AMAZON.CO.UK*1X8O02VO4  AMAZON.CO.UK'
 'AMAZON.CO.UK*HP1DE5MD5  AMAZON.CO.UK'
 'AMAZON.CO.UK*MT01N9865  AMAZON.CO.UK'
 'AMAZON.CO.UK*P87NW8EZ5  353-12477661' 'AMERICAN EXPRESS'
 'AMZ*BEST LEARNING UK    AMAZON.CO.UK'
 'AMZ*PARTY DELIGHTS L SV PAY.AMAZON.CO'
 'AMZNMKTPLACE            AMAZON.CO.UK' 'Angel Hill Site 62Farnborough'
 'APPLE.COM/BILL          HOLLYHILL'
 'APPLE.COM/BILL         08001076285   IE'
 'APPLE.COM/BILL         APPLE.COM/BIL IE                           '
 'APPLE.COM/BILL         CORK          IE                           '
 'APPLE.COM/UK            HOLLYHILL'
 'ARGOS LIMITED           MILTON KEYNES' 'Atom Easy         Atom Easy'
 'AVIOS GROUP Avios Group CRAWLEY'
 'B & Q 1076             NEW MALDEN    GB' 'B & Q 1076        NEW MALDEN'
 'B&Q NEW MALDEN 1076     NEW MALDEN' 'Babylon 76-78           London'
 'Babylon 76-78          London        GB'
 'BABYLON 76-78          LONDON  SW20  GB' 'Babylon 76-78     London'
 'BARCLAYS INSURANCE' 'BARCLAYS UK MTGES' 'Bayley and Sage   London'
 'Bayley Wimbledon       London        GB                           '
 'Bayley Wimbledon  London'
 'BB-TRAVEL INSURANC     GREAT DUNMOW  GB                           '
 "BLACKWELL'S EXETEREXETER" 'Booking.com             Amsterdam'
 'BOOTS                   BRISTOL' 'BOOTS                   NOTTINGHAM'
 'BOOTS 0853             WIMBLEDON     GB' 'BOOTS 1000        LONDON'
 'BOOTS OPTICIANS         LONDON' 'BOOTS REWARDSCHEME'
 'BOOTS THE CHEMIST       LONDON' 'BRISTOL AIRPORT SSP SAC BRISTOL'
 'BRITISH AIRWAYS GB DIRE WEST DRAYTON' 'BT GROUP PLC'
 'C1CA4 SPORTS            LONDON' 'CABVISION NETWORK LONDON'
 'CASH 0000    APR03SOUTH WEST T@13.53'
 'CASH 0000    JAN05SOUTH WEST T@11.44'
 'CASH 0000    JUN26SOUTH WEST T@09.48'
 'CASH Card    MAY05COOPERATIVE @16.05'
 'CASH Card    MAY07COOPERATIVE @12.22'
 'CASH Card    MAY09COOPERATIVE @09.57' 'CHARLOTTE TILBURY BTY   LONDON'
 'Chegworth Valley       Harrietsham   GB                           '
 'CHQ  IN AT 400704' 'CIRCOLO POPOLARE        LONDON'
 'CITY PANTRY             LONDON' 'CLEVEDON SF CONNECT     AVON'
 'CMCT CHURCH EVENTS      LONDON' 'CO-MISSION EVENTS       LONDON'
 'CO-OP GROUP 070789SHOREDITCH (S' 'CO-OP OLD STREET        LONDON'
 'CO-OP RAYNES PARK       LONDON' 'COSTA EDINBURGH AIRPORT EDINBURGH'
 'DART-CHARGE            LEEDS         GB                           '
 'DAVID LLOYD            LONDON        GB                           '
 'DAVID LLOYD LEISUR'
 'David Lloyd Leisure Li Hatfield      GB                           '
 'DAVID LLOYD LEISURE LIM HATFIELD' 'David Lloyd Raynes Park London'
 'DELIVEROO               LONDON' 'Dicky Birds       510066'
 'Dicky Birds       RORY  ADAMS' 'DISHOOM EDINBURGH       EDINBURGH'
 'DMN* PLONKGOLF-SHOREDI  COLCHESTER' 'DUNDONALD CHURCH  ADAMS'
 'EA5C9 BOOST             LONDON' 'EASYJET*EASYJET K4Q1CRP LUTON'
 'EASYJET*EASYJET K5B5WRS LUTON'
 'EDINBURGH TRAMS LIMITE EDINBURGH     GB                           '
 'EE LIMITED' 'EE LIMITED        FIRST PAYMENT'
 'ELYS                   LONDON        GB                           '
 'ELYS (WIMBLEDON) PLC    LONDON' 'EMMA BRIDGEWATER LTD    LONDON'
 'EPOSNOW*RASCALS SOFTPLA NORWICH' 'ESSO HOGS BACK SSTSURREY'
 'EXETER UNI PRINT REXETER' 'F9DDD SPORTS            LONDON'
 'FACULTY SCIENCE LIFACULTY SCIENC PAY' 'FACULTY SCIENCE LTNO REF'
 'FAMLY             FIRST PAYMENT' 'FE3FC BOOST             LONDON'
 'FINGAL                  LEITH EDINBUR' 'FIRST DIRECT VISA'
 'FIRST DIRECT VISA FIRST PAYMENT' 'FRANCO MANCA      LONDON'
 'Funding Circle UK' 'GOLFNOW                 BELFAST'
 'GOODWOOD ESTATE COMPANY CHICHESTER' 'Headmasters Wimbledon V London'
 'HM.COM                  LONDON' 'HMRC SA'
 'HOLLAND AND BARRETT     NUNEATON'
 'HOME RETAIL GROUP PLC   CENTRAL MILTON' 'HOMEOFFICE/PAYROLL'
 'IKEA LTD SHOP ONLINE   LONDON        GB                           '
 'JG *MACMILLAN CANCER S  LONDON' 'JOHN LEWIS DIRECT       LONDON'
 'JOHN LEWIS KINGSTON     KINGSTON UPON T'
 'JOJO MAMAN BEBE LTD-WIM WIMBLEDON' 'JOJO_ECOM_UK            NEWPORT'
 'Julia Adams       Money' 'Julia Adams       Playhouse'
 'JULIA MONZO       JULIA MONZO'
 'JUST PARKING LTD       LONDON        GB                           '
 'KENT PARKWOOD           CANTERBURY'
 'LA REDOUTE             BRADFORD WEST GB                           '
 'LAITHWAITES-RECURRING L READING'
 'LAKELAND.LIMITED       WINDERMERE    GB                           '
 'LARK                    LONDON'
 'LARK                   LONDON  SW20  GB' 'LB MERTON'
 'LB MERTON - RINGO PARK BASINGSTOKE   GB                           '
 'LIMPOPO BILTONG        MILTON KEYNES GB                           '
 'LOLA COFFEE             EDINBURGH'
 'LONDON BOROUGH OF      MERTON        GB                           '
 'LONDORA NAIL BOUTIQUE  WIMBLEDON     GB                           '
 'LTA Operations LimLondon' 'LUCAS CAR WASH LTD      LONDON'
 'M&S COLLIERS WOOD       LONDON' 'M&S WIMBLEDON           LONDON'
 'MARKS&SPENCER PLC SACA LONDON EC1V   GB'
 'MCDONALDS              WESTERHAM     GB                           '
 'MEDIPHARMACY           LONON         GB                           '
 'MILO S                 LONDON        GB                           '
 'MOBILE REBORN LTD 70-01-01-5496' 'Mum & Dad         NHM'
 'NEXT ONLINE NEXT APPLEP UNITED KINGDOM'
 'NO11                    EDINBURGH'
 'NYX*LRS                NewMalden     GB                           ' 'O2'
 'PAUL RAJKUMAR     DONATION' 'PAY* HANDY.COM-APR13   LONDON        GB'
 'PAY* HANDY.COM-JUN26   LONDON        GB'
 'PAY* HANDY.COM-MAY03   LONDON        GB'
 'PAY* HANDY.COM-MAY29   LONDON        GB' 'PAYMENT RECEIVED - THANK YOU'
 'PAYMENT RECEIVED - THANK YOU                                      '
 'PAYPAL *BMWORLDWIDE     01912705143'
 'PAYPAL *BODEN           4029357733'
 'PAYPAL *BQLIMITED       03330143357'
 'PAYPAL *CUTTERSQUID     02084530212' 'PAYPAL *MD UK           660494296'
 'PAYPAL *SCREWFIX        03330112112'
 'PAYPAL *TRG PLC         02031175455'
 'PAYPAL *XMASDIRECT      01350727555' 'PENNYHILL PARK SPABAGSHOT'
 'PHL & ELLAS KITCHEN     NEWTOWN'
 'Portland Scallop Compa Portland      GB                           '
 'Portland Scallop Compan Portland' 'POST OFFICE RAYNES PARK LONDON'
 'POSTMARK                LONDON'
 'POSTMARK TRADING LTD   LONDON        GB                           '
 'PRIME VIDEO *135OX6ZY4  353-12477661'
 'PRIME VIDEO *1O2VJ4UM4  353-12477661'
 'Provenance Village But London        GB                           '
 'PROVENANCE VILLAGE BUTC LONDON' 'Provenance VillageLondon'
 'Raynes Park ExpresLondon' 'Raynes Park Express     London'
 'Raynes Park Express    London        GB                           '
 'Rebecca Spence    Happy Birthday' 'RINGGO PARKING    MAIDSTONE'
 'ROBERT AND EDWARDS     LONDON  SW19  GB'
 'ROBERT AND EDWARDS LTD  LONDON' 'Ross Adams        IOU'
 'ROSS ADAMS        MONZO' 'Ross Adams        NowTV'
 'Ross Adams        Transfer' 'ROSS MONZO 2      MONZO TOP UP'
 "SAINSBURY'S LOCAL CLEVE CLEVEDON" "SAINSBURY'S LOCAL WESMI LONDON"
 "SAINSBURY'S SPRMRKTS LT LONDON" "SAINSBURY'S SUPERMARKET LONDON"
 'SAINSBURYS             RAYNES PARK   GB                           '
 'Sarah Crabtree    Picnic' 'SEPHORA UK              ST PETER'
 'SHELL ENERGY' 'SHELL PEPYS 427        LONDON SW20   GB'
 'SHELTER NAT CAMP' 'SHELTER NAT CAMP  FIRST PAYMENT'
 'SP BABY MORI LIMITED    LONDON' 'SP FRENCH CONNECTION    LONDON'
 'SP NEIGHBOURHOOD COF   LIVERPOOL     GB                           '
 'SP OMAZE UK             ALTRINCHAM'
 'SPAR                   LONDON        GB                           '
 'SPOTIFY           LONDON' 'SQ *AVIATOR HOTEL Farnborough'
 'SQ *FABULOUS COFFEE &  Whitstable    GB                           '
 'SQ *FORTITUDE COFFEE   Edinburgh     GB                           '
 'SQ *THE GREAT BIG EVEN Guildford     GB                           '
 'SQ *WIMBLEDON VILLAGE  London        GB                           '
 'STARBUCKS              LONDON        GB                           '
 'STARBUCKS BRS           BRISTOL'
 'SUMUP  *V & G ICE CREA SUTTON        GB                           '
 'SUMUP*DUNDONALD CHURCH  LONDON' 'T Archdale        Golf'
 'Tamesis Dock           London        GB                           '
 'TESCO PAY AT PUMP NEW MALDEN' 'TESCO PETROL 3883 3883T NEW MALDEN'
 'TESCO PFS 3883    NEW MALDEN' 'TESCO STORE 2934 2934TE NEW MALDEN'
 'TESCO STORE 5214 5214TE LONDON' 'TESCO STORE 6071 6071TE LONDON'
 'TESCO STORES 2288 CLEVEDON' 'TFL ENFORCEMENT OPS WEB LONDON'
 'TFL TRAVEL CH          TFL.GOV.UK/CP GB                           '
 'TFL TRAVEL CH     TFL.GOV.UK/CP' 'TFL TRAVEL CHARGE       TFL.GOV.UK/CP'
 'THAMES WATER' 'THE  WHITE  COMPANY THE UNITED KINGDOM'
 'THE CHAMPIONSHIPS, WIMB WIMBLEDON' 'THE CINNAMON TREE LTD   LONDON'
 'THE CONDE NAST PUBLICAT LONDON'
 'THE GOOD BOOK CO LTD   SURREY        GB                           '
 'THE GOOD BOOK COMPANY L Epsom' 'THE GOOD BOOK COMPANY L London'
 'THE IVY CAFE WIMBLEDON  LONDON' 'THE IVY ON THE SQUARE   EDINBURGH'
 'The Nelson Pharmacy     London' 'THE ROYAL YACHT BRITANN EDINBURGH'
 'THE ROYAL YACHT BRITANN LEITH' 'THE ROYAL YACHT BRITANN LEITH EDINBUR'
 'THE SCOTCH WHISKEY EXPE MIDLOTHIAN'
 'TM *TICKETMASTER        LOS ANGELES' 'TREATWELL               LONDON'
 'UBER TRIP               AMSTERDAM' 'UNIVERSITY OF EXETEXETER'
 'VANGUARD          LONDON' 'VANGUARD ASSET MANA06F02306050101352'
 'VANGUARD ASSET MANA06F02306050101353'
 'VANGUARD ASSET MANA06F02306050101355'
 'VANGUARD ASSET MANA06F02306050101356'
 'Vita Bella             Chelmsford    GB                           '
 'W H SMITH EUROPE TRAVEL BRISTOL' 'WAGAMAMA LIMITED        LONDON'
 'WAITROSE 0767 314N      POTTERS BAR'
 'WAITROSE 846           RAYNES PARK   GB'
 'WAITROSE RAYNES PARK    LONDON' 'WAITROSE WIMBLEDON      LONDON'
 'WEDGEWOOD               EDINBURGH'
 'Westminster Dental     London        GB                           '
 'WESTSIDE TENNIS CLUB    WIMBLEDON' 'WHITE HART HOTEL  EXETER'
 'WIMBLEDON BOOKS LTD     LONDON'
 'Wimbledon Flower Kiosk London        GB                           '
 'WINDMILL TEAROOMS      LONDON        GB                           '
 'WINDMILL TEAROOMS LONDON' 'Window Cleaner    16 Carlton Park Av'
 'WISHLIST                LONDON' 'WISLEY GLASSHOUSE CAFE  SURREY'
 'WM MORRISONS STORES     LONDON' 'WOLDINGHAM GOLF CLWOLDINGHAM CA'
 'WOODHAM MORTIMER GOLF  WOODHAM MORTI GB                           '
 'WORLD OF GOLF LONDON    NEW MALDEN'
 'WWW.ARGOS.CO.UK        MILTON KEYNES GB                           '
 'WWW.GOODEARTHGROUP.CO. LONDON  SW19  GB'
 'WWW.KIDLY.CO.UK        LONDON        GB                           '
 'WWW.PACTCOFFEE.COM      LONDON'
 'WWW.PPRUSSELLSQUARE.CO 02078333005   GB'
 'WWW.RAVECOFFEE.CO.UK   CIRENCESTERC  GB                           '
 'WWW.TAKEAWAY.JE        01534876163   GB'
 'X4139 SPORTS            LONDON'
 'ZETTLE_*CHANGO EMPANAD LONDON        GB                           '
 'Zettle_*PLONK GOLFlondon'
 'ZETTLE_*THE WILDS GROU BARNET        GB                           ']

In [3]:
TransactionDescription=H1Transactions.loc[0,'Description']
Categories=str(H1Transactions['Category'].unique())

In [66]:
# print(TransactionDescription)
print(Categories)

['Other' 'Home' 'Lunch and coffee' 'Presents' 'Savings' 'Financial gift'
 'Baby' 'Entertainment' 'Internal Transfers' 'Expenses' 'Personal Items'
 'Holidays' 'Restaurants and fast food' 'Insurance' 'Mortgage'
 'Food Shopping' 'Medical' 'Mobile/Internet' 'Income' 'Travel'
 'Sports/leisure' 'Nursery' 'Giving' 'Monzo Personal Spend' 'Council Tax'
 'Utilities' 'Books/Magazines/Papers']

In [35]:
prompt = ("Classify the following purchase description into one of the following categories in this list: (Other,Home,Lunch and coffee,Presents,Savings,Financial gift,Baby,Entertainment,Internal Transfers,Expenses,Personal Items,
Holidays,Restaurants and fast food,Insurance,Mortgage,Food Shopping,Medical,Mobile/Internet,Income,Travel,
 'Sports/leisure' 'Nursery' 'Giving' 'Monzo Personal Spend' 'Council Tax'
 'Utilities' 'Books/Magazines/Papers'). The purchase description is" + TransactionDescription)
print(prompt)

['Other' 'Home' 'Lunch and coffee' 'Presents' 'Savings' 'Financial gift'
 'Baby' 'Entertainment' 'Internal Transfers' 'Expenses' 'Personal Items'
 'Holidays' 'Restaurants and fast food' 'Insurance' 'Mortgage'
 'Food Shopping' 'Medical' 'Mobile/Internet' 'Income' 'Travel'
 'Sports/leisure' 'Nursery' 'Giving' 'Monzo Personal Spend' 'Council Tax'
 'Utilities' 'Books/Magazines/Papers']

TypeError: can only concatenate str (not "NoneType") to str

In [48]:
prompt = ("Classify the following purchase description into one of the following categories in this list:"+Categories+" The purchase description is: " + TransactionDescription)
print(prompt)

Classify the following purchase description into one of the following categories in this list:['Other' 'Home' 'Lunch and coffee' 'Presents' 'Savings' 'Financial gift'
 'Baby' 'Entertainment' 'Internal Transfers' 'Expenses' 'Personal Items'
 'Holidays' 'Restaurants and fast food' 'Insurance' 'Mortgage'
 'Food Shopping' 'Medical' 'Mobile/Internet' 'Income' 'Travel'
 'Sports/leisure' 'Nursery' 'Giving' 'Monzo Personal Spend' 'Council Tax'
 'Utilities' 'Books/Magazines/Papers'] The purchase description is: *306-0043263-0976896 M UXBRIDGE

In [40]:
# Make the API request
response = requests.post(endpoint, json=data, headers=headers)

# Check for a successful response and process the output
if response.status_code == 200:
    result = response.json()
    generated_text = result["choices"][0]["text"]
    print(generated_text)
else:
    print(f"Error: {response.status_code} - {response.text}")

coffee

In [49]:
print(prompt)

Classify the following purchase description into one of the following categories in this list:['Other' 'Home' 'Lunch and coffee' 'Presents' 'Savings' 'Financial gift'
 'Baby' 'Entertainment' 'Internal Transfers' 'Expenses' 'Personal Items'
 'Holidays' 'Restaurants and fast food' 'Insurance' 'Mortgage'
 'Food Shopping' 'Medical' 'Mobile/Internet' 'Income' 'Travel'
 'Sports/leisure' 'Nursery' 'Giving' 'Monzo Personal Spend' 'Council Tax'
 'Utilities' 'Books/Magazines/Papers'] The purchase description is: *306-0043263-0976896 M UXBRIDGE

In [59]:
def TransactionDescription(x):
    return H1Transactions.loc[x,'Description']

In [4]:
# Convert a specific column to an ordered list
TransactionDescriptionList= str(H1Transactions['Description'].tolist())

print(TransactionDescriptionList)

['*306-0043263-0976896 M UXBRIDGE', '*306-0043263-0976896 M UXBRIDGE', '*306-0043291-4166692 M UXBRIDGE', '*306-0043919-5058005 M UXBRIDGE', '0100 - COLLIERSWOOD?    COLLIERS WOOD S', '0800 HOMEFIX LTD        YATELEY', '0C385 BOOST             LONDON', '3CC5D                   LONDON', '3CPAYMENT*PRET A MANGER KINGSTON UPON T', '3CPAYMENT*STARBUCKS 127 LONDON', '3CPAYMENT*STARBUCKS 127 LONDON', '3CPAYMENT*STARBUCKS 127 LONDON', '3CPAYMENT*STARBUCKS 287 EDINBURGH', '3CPAYMENT*THE WOOLLEN M EDINBURGH', '3CPAYMENT*WELCOME BREAK HUNGERFORD', '3CPAYMENT*WELCOME BREAK POTTERS BAR', 'Absolute Taste Ltd t/a  Bicester', 'ADAMS J     *FRS  REGULAR SAVER', 'ADAMS J     *FRS  REGULAR SAVER', 'ADAMS J     *FRS  REGULAR SAVER', 'ADAMS J     *FRS  REGULAR SAVER', 'ADAMS J     *FRS  REGULAR SAVER', 'ADAMS J     *FRS  REGULAR SAVER', 'ADAMS NF&N        From Ann For Easte', 'ADAMS NF&N        Happy Anniversary', 'ADAMS NF&N        Happy Birthday', 'ADAMS R     *FRS  REGULAR ROSS', 'ADAMS R     *FRS  REGULAR ROSS', 'ADAMS R     *FRS  REGULAR ROSS', 'ADAMS R     *FRS  REGULAR ROSS', 'ADAMS R     *FRS  REGULAR ROSS', 'ADAMS R     *FRS  REGULAR ROSS', 'ALDI COLLIERS WOOD 7810 COLLIERS WOOD', 'ALDI COLLIERS WOOD 7810 COLLIERS WOOD', 'ALDI COLLIERS WOOD 7810 COLLIERS WOOD', 'ALDI COLLIERS WOOD 7810 COLLIERS WOOD', 'ALDI COLLIERS WOOD 7810 COLLIERS WOOD', 'ALDI COLLIERS WOOD 7810 COLLIERS WOOD', 'ALDI COLLIERS WOOD 7810 COLLIERS WOOD', 'ALDI COLLIERS WOOD 7810 COLLIERS WOOD', 'ALDI COLLIERS WOOD 7810 COLLIERS WOOD', 'AMAZON PRIME*1H35W84U4  AMZN.CO.UK/PM', 'AMAZON PRIME*1Q63I9T84  AMZN.CO.UK/PM', 'AMAZON PRIME*1R11Z9O64  AMZN.CO.UK/PM', 'AMAZON PRIME*9Y70Z0TD5  AMZN.CO.UK/PM', 'AMAZON PRIME*JM1BS6AB5  AMZN.CO.UK/PM', 'AMAZON PRIME*K52KN36R5  AMZN.CO.UK/PM', 'AMAZON PRIME*OY1E04205  AMZN.CO.UK/PM', 'AMAZON PRIME*R68VU5OI5  AMZN.CO.UK/PM', 'AMAZON PRIME*UX0IN94N5  AMZN.CO.UK/PM', 'AMAZON.CO.UK*015J83AB5  AMAZON.CO.UK', 'AMAZON.CO.UK*1A0AH7OW4  AMAZON.CO.UK', 'AMAZON.CO.UK*1X8O02VO4  AMAZON.CO.UK', 'AMAZON.CO.UK*HP1DE5MD5  AMAZON.CO.UK', 'AMAZON.CO.UK*MT01N9865  AMAZON.CO.UK', 'AMAZON.CO.UK*P87NW8EZ5  353-12477661', 'AMERICAN EXPRESS', 'AMERICAN EXPRESS', 'AMERICAN EXPRESS', 'AMERICAN EXPRESS', 'AMERICAN EXPRESS', 'AMERICAN EXPRESS', 'AMZ*BEST LEARNING UK    AMAZON.CO.UK', 'AMZ*BEST LEARNING UK    AMAZON.CO.UK', 'AMZ*PARTY DELIGHTS L SV PAY.AMAZON.CO', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'Angel Hill Site 62Farnborough', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL         08001076285   IE', 'APPLE.COM/BILL         08001076285   IE', 'APPLE.COM/BILL         APPLE.COM/BIL IE                           ', 'APPLE.COM/BILL         APPLE.COM/BIL IE                           ', 'APPLE.COM/BILL         CORK          IE                           ', 'APPLE.COM/BILL         CORK          IE                           ', 'APPLE.COM/UK            HOLLYHILL', 'ARGOS LIMITED           MILTON KEYNES', 'ARGOS LIMITED           MILTON KEYNES', 'ARGOS LIMITED           MILTON KEYNES', 'Atom Easy         Atom Easy', 'AVIOS GROUP Avios Group CRAWLEY', 'B & Q 1076             NEW MALDEN    GB', 'B & Q 1076             NEW MALDEN    GB', 'B & Q 1076        NEW MALDEN', 'B&Q NEW MALDEN 1076     NEW MALDEN', 'Babylon 76-78           London', 'Babylon 76-78           London', 'Babylon 76-78           London', 'Babylon 76-78           London', 'Babylon 76-78           London', 'Babylon 76-78           London', 'Babylon 76-78           London', 'Babylon 76-78           London', 'Babylon 76-78          London        GB', 'Babylon 76-78          London        GB', 'BABYLON 76-78          LONDON  SW20  GB', 'BABYLON 76-78          LONDON  SW20  GB', 'Babylon 76-78     London', 'BARCLAYS INSURANCE', 'BARCLAYS INSURANCE', 'BARCLAYS INSURANCE', 'BARCLAYS INSURANCE', 'BARCLAYS INSURANCE', 'BARCLAYS INSURANCE', 'BARCLAYS UK MTGES', 'BARCLAYS UK MTGES', 'BARCLAYS UK MTGES', 'BARCLAYS UK MTGES', 'BARCLAYS UK MTGES', 'BARCLAYS UK MTGES', 'Bayley and Sage   London', 'Bayley Wimbledon       London        GB                           ', 'Bayley Wimbledon       London        GB                           ', 'Bayley Wimbledon       London        GB                           ', 'Bayley Wimbledon  London', 'BB-TRAVEL INSURANC     GREAT DUNMOW  GB                           ', "BLACKWELL'S EXETEREXETER", 'Booking.com             Amsterdam', 'BOOTS                   BRISTOL', 'BOOTS                   BRISTOL', 'BOOTS                   NOTTINGHAM', 'BOOTS                   NOTTINGHAM', 'BOOTS 0853             WIMBLEDON     GB', 'BOOTS 0853             WIMBLEDON     GB', 'BOOTS 1000        LONDON', 'BOOTS OPTICIANS         LONDON', 'BOOTS REWARDSCHEME', 'BOOTS REWARDSCHEME', 'BOOTS REWARDSCHEME', 'BOOTS REWARDSCHEME', 'BOOTS REWARDSCHEME', 'BOOTS REWARDSCHEME', 'BOOTS THE CHEMIST       LONDON', 'BOOTS THE CHEMIST       LONDON', 'BOOTS THE CHEMIST       LONDON', 'BOOTS THE CHEMIST       LONDON', 'BOOTS THE CHEMIST       LONDON', 'BOOTS THE CHEMIST       LONDON', 'BOOTS THE CHEMIST       LONDON', 'BOOTS THE CHEMIST       LONDON', 'BOOTS THE CHEMIST       LONDON', 'BOOTS THE CHEMIST       LONDON', 'BOOTS THE CHEMIST       LONDON', 'BRISTOL AIRPORT SSP SAC BRISTOL', 'BRITISH AIRWAYS GB DIRE WEST DRAYTON', 'BRITISH AIRWAYS GB DIRE WEST DRAYTON', 'BT GROUP PLC', 'BT GROUP PLC', 'BT GROUP PLC', 'BT GROUP PLC', 'BT GROUP PLC', 'BT GROUP PLC', 'C1CA4 SPORTS            LONDON', 'CABVISION NETWORK LONDON', 'CASH 0000    APR03SOUTH WEST T@13.53', 'CASH 0000    JAN05SOUTH WEST T@11.44', 'CASH 0000    JUN26SOUTH WEST T@09.48', 'CASH Card    MAY05COOPERATIVE @16.05', 'CASH Card    MAY07COOPERATIVE @12.22', 'CASH Card    MAY09COOPERATIVE @09.57', 'CHARLOTTE TILBURY BTY   LONDON', 'Chegworth Valley       Harrietsham   GB                           ', 'CHQ  IN AT 400704', 'CIRCOLO POPOLARE        LONDON', 'CITY PANTRY             LONDON', 'CLEVEDON SF CONNECT     AVON', 'CMCT CHURCH EVENTS      LONDON', 'CMCT CHURCH EVENTS      LONDON', 'CMCT CHURCH EVENTS      LONDON', 'CO-MISSION EVENTS       LONDON', 'CO-MISSION EVENTS       LONDON', 'CO-MISSION EVENTS       LONDON', 'CO-OP GROUP 070789SHOREDITCH (S', 'CO-OP OLD STREET        LONDON', 'CO-OP RAYNES PARK       LONDON', 'CO-OP RAYNES PARK       LONDON', 'COSTA EDINBURGH AIRPORT EDINBURGH', 'DART-CHARGE            LEEDS         GB                           ', 'DAVID LLOYD            LONDON        GB                           ', 'DAVID LLOYD            LONDON        GB                           ', 'DAVID LLOYD LEISUR', 'DAVID LLOYD LEISUR', 'DAVID LLOYD LEISUR', 'DAVID LLOYD LEISUR', 'DAVID LLOYD LEISUR', 'DAVID LLOYD LEISUR', 'DAVID LLOYD LEISUR', 'David Lloyd Leisure Li Hatfield      GB                           ', 'David Lloyd Leisure Li Hatfield      GB                           ', 'David Lloyd Leisure Li Hatfield      GB                           ', 'David Lloyd Leisure Li Hatfield      GB                           ', 'David Lloyd Leisure Li Hatfield      GB                           ', 'David Lloyd Leisure Li Hatfield      GB                           ', 'David Lloyd Leisure Li Hatfield      GB                           ', 'David Lloyd Leisure Li Hatfield      GB                           ', 'David Lloyd Leisure Li Hatfield      GB                           ', 'DAVID LLOYD LEISURE LIM HATFIELD', 'DAVID LLOYD LEISURE LIM HATFIELD', 'DAVID LLOYD LEISURE LIM HATFIELD', 'David Lloyd Raynes Park London', 'DELIVEROO               LONDON', 'DELIVEROO               LONDON', 'DELIVEROO               LONDON', 'DELIVEROO               LONDON', 'Dicky Birds       510066', 'Dicky Birds       510066', 'Dicky Birds       510066', 'Dicky Birds       510066', 'Dicky Birds       510066', 'Dicky Birds       RORY  ADAMS', 'DISHOOM EDINBURGH       EDINBURGH', 'DMN* PLONKGOLF-SHOREDI  COLCHESTER', 'DMN* PLONKGOLF-SHOREDI  COLCHESTER', 'DUNDONALD CHURCH  ADAMS', 'DUNDONALD CHURCH  ADAMS', 'DUNDONALD CHURCH  ADAMS', 'DUNDONALD CHURCH  ADAMS', 'DUNDONALD CHURCH  ADAMS', 'DUNDONALD CHURCH  ADAMS', 'EA5C9 BOOST             LONDON', 'EASYJET*EASYJET K4Q1CRP LUTON', 'EASYJET*EASYJET K5B5WRS LUTON', 'EDINBURGH TRAMS LIMITE EDINBURGH     GB                           ', 'EE LIMITED', 'EE LIMITED', 'EE LIMITED', 'EE LIMITED', 'EE LIMITED        FIRST PAYMENT', 'ELYS                   LONDON        GB                           ', 'ELYS                   LONDON        GB                           ', 'ELYS                   LONDON        GB                           ', 'ELYS (WIMBLEDON) PLC    LONDON', 'ELYS (WIMBLEDON) PLC    LONDON', 'ELYS (WIMBLEDON) PLC    LONDON', 'ELYS (WIMBLEDON) PLC    LONDON', 'ELYS (WIMBLEDON) PLC    LONDON', 'ELYS (WIMBLEDON) PLC    LONDON', 'EMMA BRIDGEWATER LTD    LONDON', 'EPOSNOW*RASCALS SOFTPLA NORWICH', 'EPOSNOW*RASCALS SOFTPLA NORWICH', 'EPOSNOW*RASCALS SOFTPLA NORWICH', 'EPOSNOW*RASCALS SOFTPLA NORWICH', 'EPOSNOW*RASCALS SOFTPLA NORWICH', 'EPOSNOW*RASCALS SOFTPLA NORWICH', 'EPOSNOW*RASCALS SOFTPLA NORWICH', 'ESSO HOGS BACK SSTSURREY', 'EXETER UNI PRINT REXETER', 'F9DDD SPORTS            LONDON', 'FACULTY SCIENCE LIFACULTY SCIENC PAY', 'FACULTY SCIENCE LIFACULTY SCIENC PAY', 'FACULTY SCIENCE LIFACULTY SCIENC PAY', 'FACULTY SCIENCE LIFACULTY SCIENC PAY', 'FACULTY SCIENCE LIFACULTY SCIENC PAY', 'FACULTY SCIENCE LIFACULTY SCIENC PAY', 'FACULTY SCIENCE LTNO REF', 'FAMLY             FIRST PAYMENT', 'FE3FC BOOST             LONDON', 'FINGAL                  LEITH EDINBUR', 'FIRST DIRECT VISA', 'FIRST DIRECT VISA', 'FIRST DIRECT VISA', 'FIRST DIRECT VISA', 'FIRST DIRECT VISA FIRST PAYMENT', 'FIRST DIRECT VISA FIRST PAYMENT', 'FRANCO MANCA      LONDON', 'Funding Circle UK', 'Funding Circle UK', 'Funding Circle UK', 'GOLFNOW                 BELFAST', 'GOODWOOD ESTATE COMPANY CHICHESTER', 'Headmasters Wimbledon V London', 'HM.COM                  LONDON', 'HMRC SA', 'HMRC SA', 'HOLLAND AND BARRETT     NUNEATON', 'HOME RETAIL GROUP PLC   CENTRAL MILTON', 'HOME RETAIL GROUP PLC   CENTRAL MILTON', 'HOME RETAIL GROUP PLC   CENTRAL MILTON', 'HOME RETAIL GROUP PLC   CENTRAL MILTON', 'HOMEOFFICE/PAYROLL', 'HOMEOFFICE/PAYROLL', 'HOMEOFFICE/PAYROLL', 'HOMEOFFICE/PAYROLL', 'HOMEOFFICE/PAYROLL', 'HOMEOFFICE/PAYROLL', 'IKEA LTD SHOP ONLINE   LONDON        GB                           ', 'JG *MACMILLAN CANCER S  LONDON', 'JOHN LEWIS DIRECT       LONDON', 'JOHN LEWIS DIRECT       LONDON', 'JOHN LEWIS DIRECT       LONDON', 'JOHN LEWIS DIRECT       LONDON', 'JOHN LEWIS DIRECT       LONDON', 'JOHN LEWIS DIRECT       LONDON', 'JOHN LEWIS DIRECT       LONDON', 'JOHN LEWIS DIRECT       LONDON', 'JOHN LEWIS DIRECT       LONDON', 'JOHN LEWIS KINGSTON     KINGSTON UPON T', 'JOHN LEWIS KINGSTON     KINGSTON UPON T', 'JOJO MAMAN BEBE LTD-WIM WIMBLEDON', 'JOJO MAMAN BEBE LTD-WIM WIMBLEDON', 'JOJO MAMAN BEBE LTD-WIM WIMBLEDON', 'JOJO_ECOM_UK            NEWPORT', 'Julia Adams       Money', 'Julia Adams       Money', 'Julia Adams       Playhouse', 'Julia Adams       Playhouse', 'JULIA MONZO       JULIA MONZO', 'JULIA MONZO       JULIA MONZO', 'JULIA MONZO       JULIA MONZO', 'JULIA MONZO       JULIA MONZO', 'JULIA MONZO       JULIA MONZO', 'JULIA MONZO       JULIA MONZO', 'JULIA MONZO       JULIA MONZO', 'JUST PARKING LTD       LONDON        GB                           ', 'KENT PARKWOOD           CANTERBURY', 'KENT PARKWOOD           CANTERBURY', 'LA REDOUTE             BRADFORD WEST GB                           ', 'LAITHWAITES-RECURRING L READING', 'LAKELAND.LIMITED       WINDERMERE    GB                           ', 'LARK                    LONDON', 'LARK                    LONDON', 'LARK                    LONDON', 'LARK                    LONDON', 'LARK                    LONDON', 'LARK                    LONDON', 'LARK                   LONDON  SW20  GB', 'LB MERTON', 'LB MERTON', 'LB MERTON', 'LB MERTON', 'LB MERTON - RINGO PARK BASINGSTOKE   GB                           ', 'LB MERTON - RINGO PARK BASINGSTOKE   GB                           ', 'LB MERTON - RINGO PARK BASINGSTOKE   GB                           ', 'LB MERTON - RINGO PARK BASINGSTOKE   GB                           ', 'LIMPOPO BILTONG        MILTON KEYNES GB                           ', 'LOLA COFFEE             EDINBURGH', 'LONDON BOROUGH OF      MERTON        GB                           ', 'LONDORA NAIL BOUTIQUE  WIMBLEDON     GB                           ', 'LTA Operations LimLondon', 'LTA Operations LimLondon', 'LUCAS CAR WASH LTD      LONDON', 'M&S COLLIERS WOOD       LONDON', 'M&S WIMBLEDON           LONDON', 'M&S WIMBLEDON           LONDON', 'M&S WIMBLEDON           LONDON', 'M&S WIMBLEDON           LONDON', 'M&S WIMBLEDON           LONDON', 'M&S WIMBLEDON           LONDON', 'M&S WIMBLEDON           LONDON', 'MARKS&SPENCER PLC SACA LONDON EC1V   GB', 'MARKS&SPENCER PLC SACA LONDON EC1V   GB', 'MCDONALDS              WESTERHAM     GB                           ', 'MEDIPHARMACY           LONON         GB                           ', 'MILO S                 LONDON        GB                           ', 'MOBILE REBORN LTD 70-01-01-5496', 'Mum & Dad         NHM', 'NEXT ONLINE NEXT APPLEP UNITED KINGDOM', 'NEXT ONLINE NEXT APPLEP UNITED KINGDOM', 'NEXT ONLINE NEXT APPLEP UNITED KINGDOM', 'NO11                    EDINBURGH', 'NYX*LRS                NewMalden     GB                           ', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'PAUL RAJKUMAR     DONATION', 'PAUL RAJKUMAR     DONATION', 'PAUL RAJKUMAR     DONATION', 'PAUL RAJKUMAR     DONATION', 'PAUL RAJKUMAR     DONATION', 'PAUL RAJKUMAR     DONATION', 'PAY* HANDY.COM-APR13   LONDON        GB', 'PAY* HANDY.COM-APR13   LONDON        GB', 'PAY* HANDY.COM-JUN26   LONDON        GB', 'PAY* HANDY.COM-MAY03   LONDON        GB', 'PAY* HANDY.COM-MAY29   LONDON        GB', 'PAYMENT RECEIVED - THANK YOU', 'PAYMENT RECEIVED - THANK YOU', 'PAYMENT RECEIVED - THANK YOU', 'PAYMENT RECEIVED - THANK YOU', 'PAYMENT RECEIVED - THANK YOU', 'PAYMENT RECEIVED - THANK YOU', 'PAYMENT RECEIVED - THANK YOU                                      ', 'PAYMENT RECEIVED - THANK YOU                                      ', 'PAYMENT RECEIVED - THANK YOU                                      ', 'PAYPAL *BMWORLDWIDE     01912705143', 'PAYPAL *BODEN           4029357733', 'PAYPAL *BQLIMITED       03330143357', 'PAYPAL *CUTTERSQUID     02084530212', 'PAYPAL *CUTTERSQUID     02084530212', 'PAYPAL *MD UK           660494296', 'PAYPAL *MD UK           660494296', 'PAYPAL *SCREWFIX        03330112112', 'PAYPAL *SCREWFIX        03330112112', 'PAYPAL *SCREWFIX        03330112112', 'PAYPAL *SCREWFIX        03330112112', 'PAYPAL *TRG PLC         02031175455', 'PAYPAL *XMASDIRECT      01350727555', 'PENNYHILL PARK SPABAGSHOT', 'PHL & ELLAS KITCHEN     NEWTOWN', 'Portland Scallop Compa Portland      GB                           ', 'Portland Scallop Compa Portland      GB                           ', 'Portland Scallop Compan Portland', 'POST OFFICE RAYNES PARK LONDON', 'POSTMARK                LONDON', 'POSTMARK                LONDON', 'POSTMARK TRADING LTD   LONDON        GB                           ', 'PRIME VIDEO *135OX6ZY4  353-12477661', 'PRIME VIDEO *1O2VJ4UM4  353-12477661', 'Provenance Village But London        GB                           ', 'Provenance Village But London        GB                           ', 'Provenance Village But London        GB                           ', 'PROVENANCE VILLAGE BUTC LONDON', 'Provenance VillageLondon', 'Raynes Park ExpresLondon', 'Raynes Park Express     London', 'Raynes Park Express    London        GB                           ', 'Rebecca Spence    Happy Birthday', 'RINGGO PARKING    MAIDSTONE', 'ROBERT AND EDWARDS     LONDON  SW19  GB', 'ROBERT AND EDWARDS LTD  LONDON', 'Ross Adams        IOU', 'Ross Adams        IOU', 'Ross Adams        IOU', 'ROSS ADAMS        MONZO', 'Ross Adams        NowTV', 'Ross Adams        NowTV', 'Ross Adams        Transfer', 'ROSS MONZO 2      MONZO TOP UP', 'ROSS MONZO 2      MONZO TOP UP', 'ROSS MONZO 2      MONZO TOP UP', 'ROSS MONZO 2      MONZO TOP UP', 'ROSS MONZO 2      MONZO TOP UP', 'ROSS MONZO 2      MONZO TOP UP', "SAINSBURY'S LOCAL CLEVE CLEVEDON", "SAINSBURY'S LOCAL CLEVE CLEVEDON", "SAINSBURY'S LOCAL WESMI LONDON", "SAINSBURY'S SPRMRKTS LT LONDON", "SAINSBURY'S SUPERMARKET LONDON", "SAINSBURY'S SUPERMARKET LONDON", "SAINSBURY'S SUPERMARKET LONDON", "SAINSBURY'S SUPERMARKET LONDON", "SAINSBURY'S SUPERMARKET LONDON", "SAINSBURY'S SUPERMARKET LONDON", "SAINSBURY'S SUPERMARKET LONDON", "SAINSBURY'S SUPERMARKET LONDON", "SAINSBURY'S SUPERMARKET LONDON", "SAINSBURY'S SUPERMARKET LONDON", 'SAINSBURYS             RAYNES PARK   GB                           ', 'Sarah Crabtree    Picnic', 'SEPHORA UK              ST PETER', 'SHELL ENERGY', 'SHELL ENERGY', 'SHELL ENERGY', 'SHELL ENERGY', 'SHELL ENERGY', 'SHELL ENERGY', 'SHELL PEPYS 427        LONDON SW20   GB', 'SHELTER NAT CAMP', 'SHELTER NAT CAMP', 'SHELTER NAT CAMP', 'SHELTER NAT CAMP', 'SHELTER NAT CAMP', 'SHELTER NAT CAMP  FIRST PAYMENT', 'SP BABY MORI LIMITED    LONDON', 'SP FRENCH CONNECTION    LONDON', 'SP NEIGHBOURHOOD COF   LIVERPOOL     GB                           ', 'SP OMAZE UK             ALTRINCHAM', 'SP OMAZE UK             ALTRINCHAM', 'SPAR                   LONDON        GB                           ', 'SPOTIFY           LONDON', 'SPOTIFY           LONDON', 'SPOTIFY           LONDON', 'SPOTIFY           LONDON', 'SPOTIFY           LONDON', 'SPOTIFY           LONDON', 'SQ *AVIATOR HOTEL Farnborough', 'SQ *FABULOUS COFFEE &  Whitstable    GB                           ', 'SQ *FORTITUDE COFFEE   Edinburgh     GB                           ', 'SQ *THE GREAT BIG EVEN Guildford     GB                           ', 'SQ *THE GREAT BIG EVEN Guildford     GB                           ', 'SQ *WIMBLEDON VILLAGE  London        GB                           ', 'STARBUCKS              LONDON        GB                           ', 'STARBUCKS BRS           BRISTOL', 'SUMUP  *V & G ICE CREA SUTTON        GB                           ', 'SUMUP*DUNDONALD CHURCH  LONDON', 'SUMUP*DUNDONALD CHURCH  LONDON', 'SUMUP*DUNDONALD CHURCH  LONDON', 'SUMUP*DUNDONALD CHURCH  LONDON', 'SUMUP*DUNDONALD CHURCH  LONDON', 'SUMUP*DUNDONALD CHURCH  LONDON', 'SUMUP*DUNDONALD CHURCH  LONDON', 'T Archdale        Golf', 'Tamesis Dock           London        GB                           ', 'TESCO PAY AT PUMP NEW MALDEN', 'TESCO PETROL 3883 3883T NEW MALDEN', 'TESCO PFS 3883    NEW MALDEN', 'TESCO PFS 3883    NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO S

In [61]:
print(TransactionDescription(25))

ADAMS NF&N        Happy Birthday

In [120]:

# openai.organization = "org-0aeOV8xLMdS6EktEfObsesQ9"
# openai.api_key = os.getenv("OPENAI_API_KEY")

import requests

# Define your API key and endpoint
api_key = openai.api_key
endpoint = "https://api.openai.com/v1/completions"  # Use the appropriate endpoint for your API call

# Define your prompt or input text

# Set up the headers with your API key
headers = {
    "Authorization": f"Bearer {openai.api_key}",
    "Content-Type": "application/json",
}
Chunk=16
TransactionDescriptionList= str(H1Transactions['Description'].tolist()[(Chunk-1)*50:Chunk*50])
Categories=str(H1Transactions['Category'].unique())
# prompt = "Classify the following purchase description into one of the following categories in this list:(lunch, coffee, clothes, baby). The purchase descriptionis:('3CPAYMENT*STARBUCKS 127)"
prompt = ("I will provide you an ordered list of transaction descriptions. I would like you to return a list of values as a string to populate a new column in my table called Category, with an ordered list of Categories in the same order as the original list.  Classify the following purchase descriptions into one of the following categories in this list:"+Categories+" The purchase descriptions is: " + TransactionDescriptionList)
# Define the data for your API request
data = {
    "model": "gpt-3.5-turbo-instruct",
    "prompt": prompt,
    "max_tokens": 1500,
    "temperature": 0
}

# Make the API request
response = requests.post(endpoint, json=data, headers=headers)

# Check for a successful response and process the output
if response.status_code == 200:
    result = response.json()
    generated_text = result["choices"][0]["text"]
    print(generated_text)
else:
    print(f"Error: {response.status_code} - {response.text}")

['Presents', 'Presents', 'Presents', 'Lunch and coffee', 'Lunch and coffee', 'Food Shopping', 'Sports/leisure', 'Sports/leisure', 'Sports/leisure', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Restaurants and fast food', 'Entertainment', 'Restaurants and fast food', 'Entertainment', 'Entertainment']

In [39]:
print(TransactionDescriptionList)

['AMAZON.CO.UK*015J83AB5  AMAZON.CO.UK', 'AMAZON.CO.UK*1A0AH7OW4  AMAZON.CO.UK', 'AMAZON.CO.UK*1X8O02VO4  AMAZON.CO.UK', 'AMAZON.CO.UK*HP1DE5MD5  AMAZON.CO.UK', 'AMAZON.CO.UK*MT01N9865  AMAZON.CO.UK', 'AMAZON.CO.UK*P87NW8EZ5  353-12477661', 'AMERICAN EXPRESS', 'AMERICAN EXPRESS', 'AMERICAN EXPRESS', 'AMERICAN EXPRESS', 'AMERICAN EXPRESS', 'AMERICAN EXPRESS', 'AMZ*BEST LEARNING UK    AMAZON.CO.UK', 'AMZ*BEST LEARNING UK    AMAZON.CO.UK', 'AMZ*PARTY DELIGHTS L SV PAY.AMAZON.CO', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'Angel Hill Site 62Farnborough', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL         08001076285   IE', 'APPLE.COM/BILL         08001076285   IE', 'APPLE.COM/BILL         APPLE.COM/BIL IE                           ', 'APPLE.COM/BILL         APPLE.COM/BIL IE                           ', 'APPLE.COM/BILL         CORK          IE                           ', 'APPLE.COM/BILL         CORK          IE                           ']

In [121]:
NewCategory=generated_text.split(',')
print(len(NewCategory))
# print(NewCategory)
# # df['Split_Values'] = df['Values'].str.split(',')
# # Apply the function to create the new column
# H1Transactions['New_Category'] = H1Transactions.apply(NewCategory,axis=1)

# Save the updated DataFrame back to a CSV file
# H1Transactions.to_csv('/Users/rossadams/Documents/Finances/ExportedCSVs/FinH12023CSV/updated_Transactions-H1-Transactions.csv', index=False)
# This code will read the existing CSV file, add a new column based on your custom function, and save the updated data to a new CSV file.

# Apply the function to create the new column
# H1Transactions['NewCategory'] = H1Transactions['Category'].apply(NewCategory)

# # Save the updated DataFrame back to a CSV file
# H1Transactions.to_csv('/Users/rossadams/Documents/Finances/ExportedCSVs/FinH12023CSV/updated_Transactions-H1-Transactions.csv', index=False)

33

In [122]:
for i in range(len(NewCategory)):
    NewCategory[i] = NewCategory[i].replace('\n\n', '')
print(NewCategory)
print(len(NewCategory))

["['Presents'", " 'Presents'", " 'Presents'", " 'Lunch and coffee'", " 'Lunch and coffee'", " 'Food Shopping'", " 'Sports/leisure'", " 'Sports/leisure'", " 'Sports/leisure'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Restaurants and fast food'", " 'Entertainment'", " 'Restaurants and fast food'", " 'Entertainment'", " 'Entertainment']"]
33

In [126]:
H1Transactions.loc[(Chunk-1)*50:Chunk*50-18, 'NewCategory'] = NewCategory

H1Transactions.to_csv('/Users/rossadams/Documents/Finances/ExportedCSVs/FinH12023CSV/updated_Transactions-H1-Transactions.csv', index=False)

In [34]:
H1Transactions.head()

,Date,Description,Unnamed: 2,Amount,Net,Unnamed: 5,Category,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,NewCategory
0,18/02/2023,*306-0043263-0976896 M UXBRIDGE,MRS J ADAMS,37.5,-37.5,NaN,Other,RFI CHARGEBACK CLERK\nMARKS AND SPENCER\nALEXA...,SALFORD,M50 3SP,UNITED KINGDOM OF GB AND NI,AT230490044000011820418,General Purchases-Department Stores,['Other'
1,28/02/2023,*306-0043263-0976896 M UXBRIDGE,MRS J ADAMS,-22.5,22.5,NaN,Other,RFI CHARGEBACK CLERK\nMARKS AND SPENCER\nALEXA...,SALFORD,M50 3SP,UNITED KINGDOM OF GB AND NI,AT230600045000011947084,General Purchases-Department Stores,'Other'
2,20/02/2023,*306-0043291-4166692 M UXBRIDGE,MRS J ADAMS,22.5,-22.5,NaN,Other,RFI CHARGEBACK CLERK\nMARKS AND SPENCER\nALEXA...,SALFORD,M50 3SP,UNITED KINGDOM OF GB AND NI,AT230520048000011666062,General Purchases-Department Stores,'Other'
3,30/03/2023,*306-0043919-5058005 M UXBRIDGE,MRS J ADAMS,7.0,-7.0,NaN,Other,RFI CHARGEBACK CLERK\nMARKS AND SPENCER\nALEXA...,SALFORD,M50 3SP,UNITED KINGDOM OF GB AND NI,AT230890038000011934194,General Purchases-Department Stores,'Other'
4,18/04/2023,0100 - COLLIERSWOOD? COLLIERS WOOD S,MRS J ADAMS,16.0,-16.0,NaN,Other,UNIT 1\nTANDEM CENTRE,COLLIERSWOOD,GU,UNITED KINGDOM OF GB AND NI,AT231090028000011841574,General Purchases-Furnishing,'Restaurants and fast food'

In [51]:
print(NewCategory[0:49])

["['Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'"]

In [5]:
# Inspect the first few rows of the DataFrame to understand the data structure.
print(H1Transactions.head())

         Date                              Description   Unnamed: 2  Amount  \
0  18/02/2023          *306-0043263-0976896 M UXBRIDGE  MRS J ADAMS    37.5
1  28/02/2023          *306-0043263-0976896 M UXBRIDGE  MRS J ADAMS   -22.5
2  20/02/2023          *306-0043291-4166692 M UXBRIDGE  MRS J ADAMS    22.5
3  30/03/2023          *306-0043919-5058005 M UXBRIDGE  MRS J ADAMS     7.0
4  18/04/2023  0100 - COLLIERSWOOD?    COLLIERS WOOD S  MRS J ADAMS    16.0

    Net  Unnamed: 5 Category  \
0 -37.5         NaN    Other
1  22.5         NaN    Other
2 -22.5         NaN    Other
3  -7.0         NaN    Other
4 -16.0         NaN    Other

                                          Unnamed: 7    Unnamed: 8 Unnamed: 9  \
0  RFI CHARGEBACK CLERK\nMARKS AND SPENCER\nALEXA...       SALFORD    M50 3SP
1  RFI CHARGEBACK CLERK\nMARKS AND SPENCER\nALEXA...       SALFORD    M50 3SP
2  RFI CHARGEBACK CLERK\nMARKS AND SPENCER\nALEXA...       SALFORD    M50 3SP
3  RFI CHARGEBACK CLERK\nMARKS AND SPENCER\nALEXA...       SALFORD    M50 3SP
4                              UNIT 1\nTANDEM CENTRE  COLLIERSWOOD         GU

                   Unnamed: 10              Unnamed: 11  \
0  UNITED KINGDOM OF GB AND NI  AT230490044000011820418
1  UNITED KINGDOM OF GB AND NI  AT230600045000011947084
2  UNITED KINGDOM OF GB AND NI  AT230520048000011666062
3  UNITED KINGDOM OF GB AND NI  AT230890038000011934194
4  UNITED KINGDOM OF GB AND NI  AT231090028000011841574

                           Unnamed: 12
0  General Purchases-Department Stores
1  General Purchases-Department Stores
2  General Purchases-Department Stores
3  General Purchases-Department Stores
4         General Purchases-Furnishing

In [6]:
# Get an overview of the DataFrame, including column names and data types.
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 786 entries, 0 to 785
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         786 non-null    object
 1   Description  786 non-null    object
 2   Unnamed: 2   444 non-null    object
 3   Amount       565 non-null    float64
 4   Net          786 non-null    float64
 5   Unnamed: 5   221 non-null    float64
 6   Category     786 non-null    object
 7   Unnamed: 7   438 non-null    object
 8   Unnamed: 8   408 non-null    object
 9   Unnamed: 9   438 non-null    object
 10  Unnamed: 10  438 non-null    object
 11  Unnamed: 11  444 non-null    object
 12  Unnamed: 12  438 non-null    object
dtypes: float64(3), object(10)
memory usage: 80.0+ KB
None

In [6]:
# Get basic statistics about numerical columns in the DataFrame.
print(H1Transactions.describe())

# Check the unique values in a specific column (e.g., 'Description').
print(H1Transactions['Description'].unique())

# Check the number of rows and columns in the DataFrame.
num_rows, num_columns = H1Transactions.shape
print(f"Number of Rows: {num_rows}, Number of Columns: {num_columns}")

             Amount           Net    Unnamed: 5
count  5.650000e+02    786.000000    221.000000
mean   1.038692e+07     -7.687481   4053.549729
std    2.399262e+07    886.861405   3329.893835
min   -3.124970e+03  -9000.000000   -100.410000
25%    6.990000e+00    -44.607500    921.360000
50%    2.000000e+01    -13.245000   3686.790000
75%    1.000000e+02     -6.037500   6640.840000
max    9.959370e+07  13291.950000  14397.700000
['*306-0043263-0976896 M UXBRIDGE' '*306-0043291-4166692 M UXBRIDGE'
 '*306-0043919-5058005 M UXBRIDGE'
 '0100 - COLLIERSWOOD?    COLLIERS WOOD S'
 '0800 HOMEFIX LTD        YATELEY' '0C385 BOOST             LONDON'
 '3CC5D                   LONDON'
 '3CPAYMENT*PRET A MANGER KINGSTON UPON T'
 '3CPAYMENT*STARBUCKS 127 LONDON' '3CPAYMENT*STARBUCKS 287 EDINBURGH'
 '3CPAYMENT*THE WOOLLEN M EDINBURGH' '3CPAYMENT*WELCOME BREAK HUNGERFORD'
 '3CPAYMENT*WELCOME BREAK POTTERS BAR' 'Absolute Taste Ltd t/a  Bicester'
 'ADAMS J     *FRS  REGULAR SAVER' 'ADAMS NF&N        From Ann For Easte'
 'ADAMS NF&N        Happy Anniversary' 'ADAMS NF&N        Happy Birthday'
 'ADAMS R     *FRS  REGULAR ROSS' 'ALDI COLLIERS WOOD 7810 COLLIERS WOOD'
 'AMAZON PRIME*1H35W84U4  AMZN.CO.UK/PM'
 'AMAZON PRIME*1Q63I9T84  AMZN.CO.UK/PM'
 'AMAZON PRIME*1R11Z9O64  AMZN.CO.UK/PM'
 'AMAZON PRIME*9Y70Z0TD5  AMZN.CO.UK/PM'
 'AMAZON PRIME*JM1BS6AB5  AMZN.CO.UK/PM'
 'AMAZON PRIME*K52KN36R5  AMZN.CO.UK/PM'
 'AMAZON PRIME*OY1E04205  AMZN.CO.UK/PM'
 'AMAZON PRIME*R68VU5OI5  AMZN.CO.UK/PM'
 'AMAZON PRIME*UX0IN94N5  AMZN.CO.UK/PM'
 'AMAZON.CO.UK*015J83AB5  AMAZON.CO.UK'
 'AMAZON.CO.UK*1A0AH7OW4  AMAZON.CO.UK'
 'AMAZON.CO.UK*1X8O02VO4  AMAZON.CO.UK'
 'AMAZON.CO.UK*HP1DE5MD5  AMAZON.CO.UK'
 'AMAZON.CO.UK*MT01N9865  AMAZON.CO.UK'
 'AMAZON.CO.UK*P87NW8EZ5  353-12477661' 'AMERICAN EXPRESS'
 'AMZ*BEST LEARNING UK    AMAZON.CO.UK'
 'AMZ*PARTY DELIGHTS L SV PAY.AMAZON.CO'
 'AMZNMKTPLACE            AMAZON.CO.UK' 'Angel Hill Site 62Farnborough'
 'APPLE.COM/BILL          HOLLYHILL'
 'APPLE.COM/BILL         08001076285   IE'
 'APPLE.COM/BILL         APPLE.COM/BIL IE                           '
 'APPLE.COM/BILL         CORK          IE                           '
 'APPLE.COM/UK            HOLLYHILL'
 'ARGOS LIMITED           MILTON KEYNES' 'Atom Easy         Atom Easy'
 'AVIOS GROUP Avios Group CRAWLEY'
 'B & Q 1076             NEW MALDEN    GB' 'B & Q 1076        NEW MALDEN'
 'B&Q NEW MALDEN 1076     NEW MALDEN' 'Babylon 76-78           London'
 'Babylon 76-78          London        GB'
 'BABYLON 76-78          LONDON  SW20  GB' 'Babylon 76-78     London'
 'BARCLAYS INSURANCE' 'BARCLAYS UK MTGES' 'Bayley and Sage   London'
 'Bayley Wimbledon       London        GB                           '
 'Bayley Wimbledon  London'
 'BB-TRAVEL INSURANC     GREAT DUNMOW  GB                           '
 "BLACKWELL'S EXETEREXETER" 'Booking.com             Amsterdam'
 'BOOTS                   BRISTOL' 'BOOTS                   NOTTINGHAM'
 'BOOTS 0853             WIMBLEDON     GB' 'BOOTS 1000        LONDON'
 'BOOTS OPTICIANS         LONDON' 'BOOTS REWARDSCHEME'
 'BOOTS THE CHEMIST       LONDON' 'BRISTOL AIRPORT SSP SAC BRISTOL'
 'BRITISH AIRWAYS GB DIRE WEST DRAYTON' 'BT GROUP PLC'
 'C1CA4 SPORTS            LONDON' 'CABVISION NETWORK LONDON'
 'CASH 0000    APR03SOUTH WEST T@13.53'
 'CASH 0000    JAN05SOUTH WEST T@11.44'
 'CASH 0000    JUN26SOUTH WEST T@09.48'
 'CASH Card    MAY05COOPERATIVE @16.05'
 'CASH Card    MAY07COOPERATIVE @12.22'
 'CASH Card    MAY09COOPERATIVE @09.57' 'CHARLOTTE TILBURY BTY   LONDON'
 'Chegworth Valley       Harrietsham   GB                           '
 'CHQ  IN AT 400704' 'CIRCOLO POPOLARE        LONDON'
 'CITY PANTRY             LONDON' 'CLEVEDON SF CONNECT     AVON'
 'CMCT CHURCH EVENTS      LONDON' 'CO-MISSION EVENTS       LONDON'
 'CO-OP GROUP 070789SHOREDITCH (S' 'CO-OP OLD STREET        LONDON'
 'CO-OP RAYNES PARK       LONDON' 'COSTA EDINBURGH AIRPORT EDINBURGH'
 'DART-CHARGE            LEEDS         GB                           '
 'DAVID LLOYD            LONDON        GB                           '
 'DAVID LLOYD LEISUR'
 'David Lloyd Leisure Li Hatfield      GB                           '
 'DAVID LLOYD LEISURE LIM HATFIELD' 'David Lloyd Raynes Park London'
 'DELIVEROO               LONDON' 'Dicky Birds       510066'
 'Dicky Birds       RORY  ADAMS' 'DISHOOM EDINBURGH       EDINBURGH'
 'DMN* PLONKGOLF-SHOREDI  COLCHESTER' 'DUNDONALD CHURCH  ADAMS'
 'EA5C9 BOOST             LONDON' 'EASYJET*EASYJET K4Q1CRP LUTON'
 'EASYJET*EASYJET K5B5WRS LUTON'
 'EDINBURGH TRAMS LIMITE EDINBURGH     GB                           '
 'EE LIMITED' 'EE LIMITED        FIRST PAYMENT'
 'ELYS                   LONDON        GB                           '
 'ELYS (WIMBLEDON) PLC    LONDON' 'EMMA BRIDGEWATER LTD    LONDON'
 'EPOSNOW*RASCALS SOFTPLA NORWICH' 'ESSO HOGS BACK SSTSURREY'
 'EXETER UNI PRINT REXETER' 'F9DDD SPORTS            LONDON'
 'FACULTY SCIENCE LIFACULTY SCIENC PAY' 'FACULTY SCIENCE LTNO REF'
 'FAMLY             FIRST PAYMENT' 'FE3FC BOOST             LONDON'
 'FINGAL                  LEITH EDINBUR' 'FIRST DIRECT VISA'
 'FIRST DIRECT VISA FIRST PAYMENT' 'FRANCO MANCA      LONDON'
 'Funding Circle UK' 'GOLFNOW                 BELFAST'
 'GOODWOOD ESTATE COMPANY CHICHESTER' 'Headmasters Wimbledon V London'
 'HM.COM                  LONDON' 'HMRC SA'
 'HOLLAND AND BARRETT     NUNEATON'
 'HOME RETAIL GROUP PLC   CENTRAL MILTON' 'HOMEOFFICE/PAYROLL'
 'IKEA LTD SHOP ONLINE   LONDON        GB                           '
 'JG *MACMILLAN CANCER S  LONDON' 'JOHN LEWIS DIRECT       LONDON'
 'JOHN LEWIS KINGSTON     KINGSTON UPON T'
 'JOJO MAMAN BEBE LTD-WIM WIMBLEDON' 'JOJO_ECOM_UK            NEWPORT'
 'Julia Adams       Money' 'Julia Adams       Playhouse'
 'JULIA MONZO       JULIA MONZO'
 'JUST PARKING LTD       LONDON        GB                           '
 'KENT PARKWOOD           CANTERBURY'
 'LA REDOUTE             BRADFORD WEST GB                           '
 'LAITHWAITES-RECURRING L READING'
 'LAKELAND.LIMITED       WINDERMERE    GB                           '
 'LARK                    LONDON'
 'LARK                   LONDON  SW20  GB' 'LB MERTON'
 'LB MERTON - RINGO PARK BASINGSTOKE   GB                           '
 'LIMPOPO BILTONG        MILTON KEYNES GB                           '
 'LOLA COFFEE             EDINBURGH'
 'LONDON BOROUGH OF      MERTON        GB                           '
 'LONDORA NAIL BOUTIQUE  WIMBLEDON     GB                           '
 'LTA Operations LimLondon' 'LUCAS CAR WASH LTD      LONDON'
 'M&S COLLIERS WOOD       LONDON' 'M&S WIMBLEDON           LONDON'
 'MARKS&SPENCER PLC SACA LONDON EC1V   GB'
 'MCDONALDS              WESTERHAM     GB                           '
 'MEDIPHARMACY           LONON         GB                           '
 'MILO S                 LONDON        GB                           '
 'MOBILE REBORN LTD 70-01-01-5496' 'Mum & Dad         NHM'
 'NEXT ONLINE NEXT APPLEP UNITED KINGDOM'
 'NO11                    EDINBURGH'
 'NYX*LRS                NewMalden     GB                           ' 'O2'
 'PAUL RAJKUMAR     DONATION' 'PAY* HANDY.COM-APR13   LONDON        GB'
 'PAY* HANDY.COM-JUN26   LONDON        GB'
 'PAY* HANDY.COM-MAY03   LONDON        GB'
 'PAY* HANDY.COM-MAY29   LONDON        GB' 'PAYMENT RECEIVED - THANK YOU'
 'PAYMENT RECEIVED - THANK YOU                                      '
 'PAYPAL *BMWORLDWIDE     01912705143'
 'PAYPAL *BODEN           4029357733'
 'PAYPAL *BQLIMITED       03330143357'
 'PAYPAL *CUTTERSQUID     02084530212' 'PAYPAL *MD UK           660494296'
 'PAYPAL *SCREWFIX        03330112112'
 'PAYPAL *TRG PLC         02031175455'
 'PAYPAL *XMASDIRECT      01350727555' 'PENNYHILL PARK SPABAGSHOT'
 'PHL & ELLAS KITCHEN     NEWTOWN'
 'Portland Scallop Compa Portland      GB                           '
 'Portland Scallop Compan Portland' 'POST OFFICE RAYNES PARK LONDON'
 'POSTMARK                LONDON'
 'POSTMARK TRADING LTD   LONDON        GB                           '
 'PRIME VIDEO *135OX6ZY4  353-12477661'
 'PRIME VIDEO *1O2VJ4UM4  353-12477661'
 'Provenance Village But London        GB                           '
 'PROVENANCE VILLAGE BUTC LONDON' 'Provenance VillageLondon'
 'Raynes Park ExpresLondon' 'Raynes Park Express     London'
 'Raynes Park Express    London        GB                           '
 'Rebecca Spence    Happy Birthday' 'RINGGO PARKING    MAIDSTONE'
 'ROBERT AND EDWARDS     LONDON  SW19  GB'
 'ROBERT AND EDWARDS LTD  LONDON' 'Ross Adams        IOU'
 'ROSS ADAMS        MONZO' 'Ross Adams        NowTV'
 'Ross Adams        Transfer' 'ROSS MONZO 2      MONZO TOP UP'
 "SAINSBURY'S LOCAL CLEVE CLEVEDON" "SAINSBURY'S LOCAL WESMI LONDON"
 "SAINSBURY'S SPRMRKTS LT LONDON" "SAINSBURY'S SUPERMARKET LONDON"
 'SAINSBURYS             RAYNES PARK   GB                           '
 'Sarah Crabtree    Picnic' 'SEPHORA UK              ST PETER'
 'SHELL ENERGY' 'SHELL PEPYS 427        LONDON SW20   GB'
 'SHELTER NAT CAMP' 'SHELTER NAT CAMP  FIRST PAYMENT'
 'SP BABY MORI LIMITED    LONDON' 'SP FRENCH CONNECTION    LONDON'
 'SP NEIGHBOURHOOD COF   LIVERPOOL     GB                           '
 'SP OMAZE UK             ALTRINCHAM'
 'SPAR                   LONDON        GB                           '
 'SPOTIFY           LONDON' 'SQ *AVIATOR HOTEL Farnborough'
 'SQ *FABULOUS COFFEE &  Whitstable    GB                           '
 'SQ *FORTITUDE COFFEE   Edinburgh     GB                           '
 'SQ *THE GREAT BIG EVEN Guildford     GB                           '
 'SQ *WIMBLEDON VILLAGE  London        GB                           '
 'STARBUCKS              LONDON        GB                           '
 'STARBUCKS BRS           BRISTOL'
 'SUMUP  *V & G ICE CREA SUTTON        GB                           '
 'SUMUP*DUNDONALD CHURCH  LONDON' 'T Archdale        Golf'
 'Tamesis Dock           London        GB                           '
 'TESCO PAY AT PUMP NEW MALDEN' 'TESCO PETROL 3883 3883T NEW MALDEN'
 'TESCO PFS 3883    NEW MALDEN' 'TESCO STORE 2934 2934TE NEW MALDEN'
 'TESCO STORE 5214 5214TE LONDON' 'TESCO STORE 6071 6071TE LONDON'
 'TESCO STORES 2288 CLEVEDON' 'TFL ENFORCEMENT OPS WEB LONDON'
 'TFL TRAVEL CH          TFL.GOV.UK/CP GB                           '
 'TFL TRAVEL CH     TFL.GOV.UK/CP' 'TFL TRAVEL CHARGE       TFL.GOV.UK/CP'
 'THAMES WATER' 'THE  WHITE  COMPANY THE UNITED KINGDOM'
 'THE CHAMPIONSHIPS, WIMB WIMBLEDON' 'THE CINNAMON TREE LTD   LONDON'
 'THE CONDE NAST PUBLICAT LONDON'
 'THE GOOD BOOK CO LTD   SURREY        GB                           '
 'THE GOOD BOOK COMPANY L Epsom' 'THE GOOD BOOK COMPANY L London'
 'THE IVY CAFE WIMBLEDON  LONDON' 'THE IVY ON THE SQUARE   EDINBURGH'
 'The Nelson Pharmacy     London' 'THE ROYAL YACHT BRITANN EDINBURGH'
 'THE ROYAL YACHT BRITANN LEITH' 'THE ROYAL YACHT BRITANN LEITH EDINBUR'
 'THE SCOTCH WHISKEY EXPE MIDLOTHIAN'
 'TM *TICKETMASTER        LOS ANGELES' 'TREATWELL               LONDON'
 'UBER TRIP               AMSTERDAM' 'UNIVERSITY OF EXETEXETER'
 'VANGUARD          LONDON' 'VANGUARD ASSET MANA06F02306050101352'
 'VANGUARD ASSET MANA06F02306050101353'
 'VANGUARD ASSET MANA06F02306050101355'
 'VANGUARD ASSET MANA06F02306050101356'
 'Vita Bella             Chelmsford    GB                           '
 'W H SMITH EUROPE TRAVEL BRISTOL' 'WAGAMAMA LIMITED        LONDON'
 'WAITROSE 0767 314N      POTTERS BAR'
 'WAITROSE 846           RAYNES PARK   GB'
 'WAITROSE RAYNES PARK    LONDON' 'WAITROSE WIMBLEDON      LONDON'
 'WEDGEWOOD               EDINBURGH'
 'Westminster Dental     London        GB                           '
 'WESTSIDE TENNIS CLUB    WIMBLEDON' 'WHITE HART HOTEL  EXETER'
 'WIMBLEDON BOOKS LTD     LONDON'
 'Wimbledon Flower Kiosk London        GB                           '
 'WINDMILL TEAROOMS      LONDON        GB                           '
 'WINDMILL TEAROOMS LONDON' 'Window Cleaner    16 Carlton Park Av'
 'WISHLIST                LONDON' 'WISLEY GLASSHOUSE CAFE  SURREY'
 'WM MORRISONS STORES     LONDON' 'WOLDINGHAM GOLF CLWOLDINGHAM CA'
 'WOODHAM MORTIMER GOLF  WOODHAM MORTI GB                           '
 'WORLD OF GOLF LONDON    NEW MALDEN'
 'WWW.ARGOS.CO.UK        MILTON KEYNES GB                           '
 'WWW.GOODEARTHGROUP.CO. LONDON  SW19  GB'
 'WWW.KIDLY.CO.UK        LONDON        GB                           '
 'WWW.PACTCOFFEE.COM      LONDON'
 'WWW.PPRUSSELLSQUARE.CO 02078333005   GB'
 'WWW.RAVECOFFEE.CO.UK   CIRENCESTERC  GB                           '
 'WWW.TAKEAWAY.JE        01534876163   GB'
 'X4139 SPORTS            LONDON'
 'ZETTLE_*CHANGO EMPANAD LONDON        GB                           '
 'Zettle_*PLONK GOLFlondon'
 'ZETTLE_*THE WILDS GROU BARNET        GB                           ']
Number of Rows: 786, Number of Columns: 13

In [2]:
import os
import openai

In [4]:
openai.Model.list()

<OpenAIObject list at 0x7fc12d7d4220> JSON: {
  "object": "list",
  "data": [
    {
      "id": "text-search-babbage-doc-001",
      "object": "model",
      "created": 1651172509,
      "owned_by": "openai-dev"
    },
    {
      "id": "gpt-3.5-turbo-16k-0613",
      "object": "model",
      "created": 1685474247,
      "owned_by": "openai"
    },
    {
      "id": "curie-search-query",
      "object": "model",
      "created": 1651172509,
      "owned_by": "openai-dev"
    },
    {
      "id": "gpt-3.5-turbo-16k",
      "object": "model",
      "created": 1683758102,
      "owned_by": "openai-internal"
    },
    {
      "id": "text-search-babbage-query-001",
      "object": "model",
      "created": 1651172509,
      "owned_by": "openai-dev"
    },
    {
      "id": "babbage",
      "object": "model",
      "created": 1649358449,
      "owned_by": "openai"
    },
    {
      "id": "babbage-search-query",
      "object": "model",
      "created": 1651172509,
      "owned_by": "openai-dev"
    },
    {
      "id": "text-babbage-001",
      "object": "model",
      "created": 1649364043,
      "owned_by": "openai"
    },
    {
      "id": "whisper-1",
      "object": "model",
      "created": 1677532384,
      "owned_by": "openai-internal"
    },
    {
      "id": "text-similarity-davinci-001",
      "object": "model",
      "created": 1651172505,
      "owned_by": "openai-dev"
    },
    {
      "id": "davinci-similarity",
      "object": "model",
      "created": 1651172509,
      "owned_by": "openai-dev"
    },
    {
      "id": "code-davinci-edit-001",
      "object": "model",
      "created": 1649880484,
      "owned_by": "openai"
    },
    {
      "id": "curie-similarity",
      "object": "model",
      "created": 1651172510,
      "owned_by": "openai-dev"
    },
    {
      "id": "babbage-search-document",
      "object": "model",
      "created": 1651172510,
      "owned_by": "openai-dev"
    },
    {
      "id": "curie-instruct-beta",
      "object": "model",
      "created": 1649364042,
      "owned_by": "openai"
    },
    {
      "id": "text-search-ada-doc-001",
      "object": "model",
      "created": 1651172507,
      "owned_by": "openai-dev"
    },
    {
      "id": "davinci-instruct-beta",
      "object": "model",
      "created": 1649364042,
      "owned_by": "openai"
    },
    {
      "id": "text-similarity-babbage-001",
      "object": "model",
      "created": 1651172505,
      "owned_by": "openai-dev"
    },
    {
      "id": "text-search-davinci-doc-001",
      "object": "model",
      "created": 1651172505,
      "owned_by": "openai-dev"
    },
    {
      "id": "babbage-similarity",
      "object": "model",
      "created": 1651172505,
      "owned_by": "openai-dev"
    },
    {
      "id": "text-embedding-ada-002",
      "object": "model",
      "created": 1671217299,
      "owned_by": "openai-internal"
    },
    {
      "id": "davinci-search-query",
      "object": "model",
      "created": 1651172505,
      "owned_by": "openai-dev"
    },
    {
      "id": "text-similarity-curie-001",
      "object": "model",
      "created": 1651172507,
      "owned_by": "openai-dev"
    },
    {
      "id": "text-davinci-001",
      "object": "model",
      "created": 1649364042,
      "owned_by": "openai"
    },
    {
      "id": "text-search-davinci-query-001",
      "object": "model",
      "created": 1651172505,
      "owned_by": "openai-dev"
    },
    {
      "id": "ada-search-document",
      "object": "model",
      "created": 1651172507,
      "owned_by": "openai-dev"
    },
    {
      "id": "ada-code-search-code",
      "object": "model",
      "created": 1651172505,
      "owned_by": "openai-dev"
    },
    {
      "id": "babbage-002",
      "object": "model",
      "created": 1692634615,
      "owned_by": "system"
    },
    {
      "id": "davinci-002",
      "object": "model",
      "created": 1692634301,
      "owned_by": "system"
    },
    {
      "id": "davinci-search-document",
      "object": "model",
      "created": 1651172509,
      "owned_by": "openai-dev"
    },
    {
      "id": "curie-search-document",
      "object": "model",
      "created": 1651172508,
      "owned_by": "openai-dev"
    },
    {
      "id": "babbage-code-search-code",
      "object": "model",
      "created": 1651172509,
      "owned_by": "openai-dev"
    },
    {
      "id": "text-search-ada-query-001",
      "object": "model",
      "created": 1651172505,
      "owned_by": "openai-dev"
    },
    {
      "id": "code-search-ada-text-001",
      "object": "model",
      "created": 1651172507,
      "owned_by": "openai-dev"
    },
    {
      "id": "babbage-code-search-text",
      "object": "model",
      "created": 1651172509,
      "owned_by": "openai-dev"
    },
    {
      "id": "code-search-babbage-code-001",
      "object": "model",
      "created": 1651172507,
      "owned_by": "openai-dev"
    },
    {
      "id": "ada-search-query",
      "object": "model",
      "created": 1651172505,
      "owned_by": "openai-dev"
    },
    {
      "id": "ada-code-search-text",
      "object": "model",
      "created": 1651172510,
      "owned_by": "openai-dev"
    },
    {
      "id": "text-search-curie-query-001",
      "object": "model",
      "created": 1651172509,
      "owned_by": "openai-dev"
    },
    {
      "id": "text-davinci-002",
      "object": "model",
      "created": 1649880484,
      "owned_by": "openai"
    },
    {
      "id": "text-davinci-edit-001",
      "object": "model",
      "created": 1649809179,
      "owned_by": "openai"
    },
    {
      "id": "code-search-babbage-text-001",
      "object": "model",
      "created": 1651172507,
      "owned_by": "openai-dev"
    },
    {
      "id": "gpt-3.5-turbo",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "gpt-3.5-turbo-instruct-0914",
      "object": "model",
      "created": 1694122472,
      "owned_by": "system"
    },
    {
      "id": "ada",
      "object": "model",
      "created": 1649357491,
      "owned_by": "openai"
    },
    {
      "id": "text-ada-001",
      "object": "model",
      "created": 1649364042,
      "owned_by": "openai"
    },
    {
      "id": "ada-similarity",
      "object": "model",
      "created": 1651172507,
      "owned_by": "openai-dev"
    },
    {
      "id": "code-search-ada-code-001",
      "object": "model",
      "created": 1651172507,
      "owned_by": "openai-dev"
    },
    {
      "id": "text-similarity-ada-001",
      "object": "model",
      "created": 1651172505,
      "owned_by": "openai-dev"
    },
    {
      "id": "gpt-3.5-turbo-0301",
      "object": "model",
      "created": 1677649963,
      "owned_by": "openai"
    },
    {
      "id": "gpt-3.5-turbo-instruct",
      "object": "model",
      "created": 1692901427,
      "owned_by": "system"
    },
    {
      "id": "text-search-curie-doc-001",
      "object": "model",
      "created": 1651172509,
      "owned_by": "openai-dev"
    },
    {
      "id": "text-davinci-003",
      "object": "model",
      "created": 1669599635,
      "owned_by": "openai-internal"
    },
    {
      "id": "text-curie-001",
      "object": "model",
      "created": 1649364043,
      "owned_by": "openai"
    },
    {
      "id": "curie",
      "object": "model",
      "created": 1649359874,
      "owned_by": "openai"
    },
    {
      "id": "davinci",
      "object": "model",
      "created": 1649359874,
      "owned_by": "openai"
    },
    {
      "id": "dall-e-2",
      "object": "model",
      "created": 1698798177,
      "owned_by": "system"
    },
    {
      "id": "gpt-3.5-turbo-0613",
      "object": "model",
      "created": 1686587434,
      "owned_by": "openai"
    }
  ]
}

In [51]:
# import requests

# # Define your API key and endpoint
# 
# endpoint = "https://api.openai.com/v1/completions"  # Use the appropriate endpoint for your API call

# # Define your prompt or input text
# # prompt = "Classify the following purchase description into one of the following categories in this list:(lunch, coffee, clothes, baby). The purchase descriptionis:('3CPAYMENT*STARBUCKS 127)"

# # Define the data for your API request
# data = {
#     "model": "gpt-3.5-turbo-instruct",
#     "prompt": prompt,
#     "max_tokens": 20,
#     "temperature": 0
# }

# # Set up the headers with your API key
# headers = {
#     "Authorization": f"Bearer {openai.api_key}",
#     "Content-Type": "application/json",
# }

# # Make the API request
# response = requests.post(endpoint, json=data, headers=headers)

# # Check for a successful response and process the output
# if response.status_code == 200:
#     result = response.json()
#     generated_text = result["choices"][0]["text"]
#     print(generated_text)
# else:
#     print(f"Error: {response.status_code} - {response.text}")

 GB


Other

In [8]:
prompt="Hello, how are you?"
data = {
    "model": "gpt-3.5-turbo-instruct",
    "prompt": prompt,
    "max_tokens": 20,
    "temperature": 0
}
# Make the API request
response = requests.post(endpoint, json=data, headers=headers)

In [9]:
print(headers)

{'Authorization': 'Bearer REMOVED', 'Content-Type': 'application/json'}

In [10]:
print(data)

{'model': 'gpt-3.5-turbo-instruct', 'prompt': 'Hello, how are you?', 'max_tokens': 20, 'temperature': 0}

In [11]:
print(json)

NameError: name 'json' is not defined

In [16]:
response = requests.post(endpoint, json=data, headers=headers)
if response.status_code == 200:
    result = response.json()
    print(result)
else:
    print(f"Error: {response.status_code} - {response.text}")

Error: 400 - {
  "error": {
    "message": "'messages' is a required property",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

In [42]:
print(data)

{'model': 'gpt-3.5-turbo-instruct', 'prompt': "Classify the following purchase description into one of the following categories in this list:(lunch, coffee, clothes, baby). The purchase descriptionis:('3CPAYMENT*STARBUCKS 127)", 'max_tokens': 20, 'temperature': 0}

In [24]:
print(H1Transactions['Description'].unique())

['*306-0043263-0976896 M UXBRIDGE' '*306-0043291-4166692 M UXBRIDGE'
 '*306-0043919-5058005 M UXBRIDGE'
 '0100 - COLLIERSWOOD?    COLLIERS WOOD S'
 '0800 HOMEFIX LTD        YATELEY' '0C385 BOOST             LONDON'
 '3CC5D                   LONDON'
 '3CPAYMENT*PRET A MANGER KINGSTON UPON T'
 '3CPAYMENT*STARBUCKS 127 LONDON' '3CPAYMENT*STARBUCKS 287 EDINBURGH'
 '3CPAYMENT*THE WOOLLEN M EDINBURGH' '3CPAYMENT*WELCOME BREAK HUNGERFORD'
 '3CPAYMENT*WELCOME BREAK POTTERS BAR' 'Absolute Taste Ltd t/a  Bicester'
 'ADAMS J     *FRS  REGULAR SAVER' 'ADAMS NF&N        From Ann For Easte'
 'ADAMS NF&N        Happy Anniversary' 'ADAMS NF&N        Happy Birthday'
 'ADAMS R     *FRS  REGULAR ROSS' 'ALDI COLLIERS WOOD 7810 COLLIERS WOOD'
 'AMAZON PRIME*1H35W84U4  AMZN.CO.UK/PM'
 'AMAZON PRIME*1Q63I9T84  AMZN.CO.UK/PM'
 'AMAZON PRIME*1R11Z9O64  AMZN.CO.UK/PM'
 'AMAZON PRIME*9Y70Z0TD5  AMZN.CO.UK/PM'
 'AMAZON PRIME*JM1BS6AB5  AMZN.CO.UK/PM'
 'AMAZON PRIME*K52KN36R5  AMZN.CO.UK/PM'
 'AMAZON PRIME*OY1E04205  AMZN.CO.UK/PM'
 'AMAZON PRIME*R68VU5OI5  AMZN.CO.UK/PM'
 'AMAZON PRIME*UX0IN94N5  AMZN.CO.UK/PM'
 'AMAZON.CO.UK*015J83AB5  AMAZON.CO.UK'
 'AMAZON.CO.UK*1A0AH7OW4  AMAZON.CO.UK'
 'AMAZON.CO.UK*1X8O02VO4  AMAZON.CO.UK'
 'AMAZON.CO.UK*HP1DE5MD5  AMAZON.CO.UK'
 'AMAZON.CO.UK*MT01N9865  AMAZON.CO.UK'
 'AMAZON.CO.UK*P87NW8EZ5  353-12477661' 'AMERICAN EXPRESS'
 'AMZ*BEST LEARNING UK    AMAZON.CO.UK'
 'AMZ*PARTY DELIGHTS L SV PAY.AMAZON.CO'
 'AMZNMKTPLACE            AMAZON.CO.UK' 'Angel Hill Site 62Farnborough'
 'APPLE.COM/BILL          HOLLYHILL'
 'APPLE.COM/BILL         08001076285   IE'
 'APPLE.COM/BILL         APPLE.COM/BIL IE                           '
 'APPLE.COM/BILL         CORK          IE                           '
 'APPLE.COM/UK            HOLLYHILL'
 'ARGOS LIMITED           MILTON KEYNES' 'Atom Easy         Atom Easy'
 'AVIOS GROUP Avios Group CRAWLEY'
 'B & Q 1076             NEW MALDEN    GB' 'B & Q 1076        NEW MALDEN'
 'B&Q NEW MALDEN 1076     NEW MALDEN' 'Babylon 76-78           London'
 'Babylon 76-78          London        GB'
 'BABYLON 76-78          LONDON  SW20  GB' 'Babylon 76-78     London'
 'BARCLAYS INSURANCE' 'BARCLAYS UK MTGES' 'Bayley and Sage   London'
 'Bayley Wimbledon       London        GB                           '
 'Bayley Wimbledon  London'
 'BB-TRAVEL INSURANC     GREAT DUNMOW  GB                           '
 "BLACKWELL'S EXETEREXETER" 'Booking.com             Amsterdam'
 'BOOTS                   BRISTOL' 'BOOTS                   NOTTINGHAM'
 'BOOTS 0853             WIMBLEDON     GB' 'BOOTS 1000        LONDON'
 'BOOTS OPTICIANS         LONDON' 'BOOTS REWARDSCHEME'
 'BOOTS THE CHEMIST       LONDON' 'BRISTOL AIRPORT SSP SAC BRISTOL'
 'BRITISH AIRWAYS GB DIRE WEST DRAYTON' 'BT GROUP PLC'
 'C1CA4 SPORTS            LONDON' 'CABVISION NETWORK LONDON'
 'CASH 0000    APR03SOUTH WEST T@13.53'
 'CASH 0000    JAN05SOUTH WEST T@11.44'
 'CASH 0000    JUN26SOUTH WEST T@09.48'
 'CASH Card    MAY05COOPERATIVE @16.05'
 'CASH Card    MAY07COOPERATIVE @12.22'
 'CASH Card    MAY09COOPERATIVE @09.57' 'CHARLOTTE TILBURY BTY   LONDON'
 'Chegworth Valley       Harrietsham   GB                           '
 'CHQ  IN AT 400704' 'CIRCOLO POPOLARE        LONDON'
 'CITY PANTRY             LONDON' 'CLEVEDON SF CONNECT     AVON'
 'CMCT CHURCH EVENTS      LONDON' 'CO-MISSION EVENTS       LONDON'
 'CO-OP GROUP 070789SHOREDITCH (S' 'CO-OP OLD STREET        LONDON'
 'CO-OP RAYNES PARK       LONDON' 'COSTA EDINBURGH AIRPORT EDINBURGH'
 'DART-CHARGE            LEEDS         GB                           '
 'DAVID LLOYD            LONDON        GB                           '
 'DAVID LLOYD LEISUR'
 'David Lloyd Leisure Li Hatfield      GB                           '
 'DAVID LLOYD LEISURE LIM HATFIELD' 'David Lloyd Raynes Park London'
 'DELIVEROO               LONDON' 'Dicky Birds       510066'
 'Dicky Birds       RORY  ADAMS' 'DISHOOM EDINBURGH       EDINBURGH'
 'DMN* PLONKGOLF-SHOREDI  COLCHESTER' 'DUNDONALD CHURCH  ADAMS'
 'EA5C9 BOOST             LONDON' 'EASYJET*EASYJET K4Q1CRP LUTON'
 'EASYJET*EASYJET K5B5WRS LUTON'
 'EDINBURGH TRAMS LIMITE EDINBURGH     GB                           '
 'EE LIMITED' 'EE LIMITED        FIRST PAYMENT'
 'ELYS                   LONDON        GB                           '
 'ELYS (WIMBLEDON) PLC    LONDON' 'EMMA BRIDGEWATER LTD    LONDON'
 'EPOSNOW*RASCALS SOFTPLA NORWICH' 'ESSO HOGS BACK SSTSURREY'
 'EXETER UNI PRINT REXETER' 'F9DDD SPORTS            LONDON'
 'FACULTY SCIENCE LIFACULTY SCIENC PAY' 'FACULTY SCIENCE LTNO REF'
 'FAMLY             FIRST PAYMENT' 'FE3FC BOOST             LONDON'
 'FINGAL                  LEITH EDINBUR' 'FIRST DIRECT VISA'
 'FIRST DIRECT VISA FIRST PAYMENT' 'FRANCO MANCA      LONDON'
 'Funding Circle UK' 'GOLFNOW                 BELFAST'
 'GOODWOOD ESTATE COMPANY CHICHESTER' 'Headmasters Wimbledon V London'
 'HM.COM                  LONDON' 'HMRC SA'
 'HOLLAND AND BARRETT     NUNEATON'
 'HOME RETAIL GROUP PLC   CENTRAL MILTON' 'HOMEOFFICE/PAYROLL'
 'IKEA LTD SHOP ONLINE   LONDON        GB                           '
 'JG *MACMILLAN CANCER S  LONDON' 'JOHN LEWIS DIRECT       LONDON'
 'JOHN LEWIS KINGSTON     KINGSTON UPON T'
 'JOJO MAMAN BEBE LTD-WIM WIMBLEDON' 'JOJO_ECOM_UK            NEWPORT'
 'Julia Adams       Money' 'Julia Adams       Playhouse'
 'JULIA MONZO       JULIA MONZO'
 'JUST PARKING LTD       LONDON        GB                           '
 'KENT PARKWOOD           CANTERBURY'
 'LA REDOUTE             BRADFORD WEST GB                           '
 'LAITHWAITES-RECURRING L READING'
 'LAKELAND.LIMITED       WINDERMERE    GB                           '
 'LARK                    LONDON'
 'LARK                   LONDON  SW20  GB' 'LB MERTON'
 'LB MERTON - RINGO PARK BASINGSTOKE   GB                           '
 'LIMPOPO BILTONG        MILTON KEYNES GB                           '
 'LOLA COFFEE             EDINBURGH'
 'LONDON BOROUGH OF      MERTON        GB                           '
 'LONDORA NAIL BOUTIQUE  WIMBLEDON     GB                           '
 'LTA Operations LimLondon' 'LUCAS CAR WASH LTD      LONDON'
 'M&S COLLIERS WOOD       LONDON' 'M&S WIMBLEDON           LONDON'
 'MARKS&SPENCER PLC SACA LONDON EC1V   GB'
 'MCDONALDS              WESTERHAM     GB                           '
 'MEDIPHARMACY           LONON         GB                           '
 'MILO S                 LONDON        GB                           '
 'MOBILE REBORN LTD 70-01-01-5496' 'Mum & Dad         NHM'
 'NEXT ONLINE NEXT APPLEP UNITED KINGDOM'
 'NO11                    EDINBURGH'
 'NYX*LRS                NewMalden     GB                           ' 'O2'
 'PAUL RAJKUMAR     DONATION' 'PAY* HANDY.COM-APR13   LONDON        GB'
 'PAY* HANDY.COM-JUN26   LONDON        GB'
 'PAY* HANDY.COM-MAY03   LONDON        GB'
 'PAY* HANDY.COM-MAY29   LONDON        GB' 'PAYMENT RECEIVED - THANK YOU'
 'PAYMENT RECEIVED - THANK YOU                                      '
 'PAYPAL *BMWORLDWIDE     01912705143'
 'PAYPAL *BODEN           4029357733'
 'PAYPAL *BQLIMITED       03330143357'
 'PAYPAL *CUTTERSQUID     02084530212' 'PAYPAL *MD UK           660494296'
 'PAYPAL *SCREWFIX        03330112112'
 'PAYPAL *TRG PLC         02031175455'
 'PAYPAL *XMASDIRECT      01350727555' 'PENNYHILL PARK SPABAGSHOT'
 'PHL & ELLAS KITCHEN     NEWTOWN'
 'Portland Scallop Compa Portland      GB                           '
 'Portland Scallop Compan Portland' 'POST OFFICE RAYNES PARK LONDON'
 'POSTMARK                LONDON'
 'POSTMARK TRADING LTD   LONDON        GB                           '
 'PRIME VIDEO *135OX6ZY4  353-12477661'
 'PRIME VIDEO *1O2VJ4UM4  353-12477661'
 'Provenance Village But London        GB                           '
 'PROVENANCE VILLAGE BUTC LONDON' 'Provenance VillageLondon'
 'Raynes Park ExpresLondon' 'Raynes Park Express     London'
 'Raynes Park Express    London        GB                           '
 'Rebecca Spence    Happy Birthday' 'RINGGO PARKING    MAIDSTONE'
 'ROBERT AND EDWARDS     LONDON  SW19  GB'
 'ROBERT AND EDWARDS LTD  LONDON' 'Ross Adams        IOU'
 'ROSS ADAMS        MONZO' 'Ross Adams        NowTV'
 'Ross Adams        Transfer' 'ROSS MONZO 2      MONZO TOP UP'
 "SAINSBURY'S LOCAL CLEVE CLEVEDON" "SAINSBURY'S LOCAL WESMI LONDON"
 "SAINSBURY'S SPRMRKTS LT LONDON" "SAINSBURY'S SUPERMARKET LONDON"
 'SAINSBURYS             RAYNES PARK   GB                           '
 'Sarah Crabtree    Picnic' 'SEPHORA UK              ST PETER'
 'SHELL ENERGY' 'SHELL PEPYS 427        LONDON SW20   GB'
 'SHELTER NAT CAMP' 'SHELTER NAT CAMP  FIRST PAYMENT'
 'SP BABY MORI LIMITED    LONDON' 'SP FRENCH CONNECTION    LONDON'
 'SP NEIGHBOURHOOD COF   LIVERPOOL     GB                           '
 'SP OMAZE UK             ALTRINCHAM'
 'SPAR                   LONDON        GB                           '
 'SPOTIFY           LONDON' 'SQ *AVIATOR HOTEL Farnborough'
 'SQ *FABULOUS COFFEE &  Whitstable    GB                           '
 'SQ *FORTITUDE COFFEE   Edinburgh     GB                           '
 'SQ *THE GREAT BIG EVEN Guildford     GB                           '
 'SQ *WIMBLEDON VILLAGE  London        GB                           '
 'STARBUCKS              LONDON        GB                           '
 'STARBUCKS BRS           BRISTOL'
 'SUMUP  *V & G ICE CREA SUTTON        GB                           '
 'SUMUP*DUNDONALD CHURCH  LONDON' 'T Archdale        Golf'
 'Tamesis Dock           London        GB                           '
 'TESCO PAY AT PUMP NEW MALDEN' 'TESCO PETROL 3883 3883T NEW MALDEN'
 'TESCO PFS 3883    NEW MALDEN' 'TESCO STORE 2934 2934TE NEW MALDEN'
 'TESCO STORE 5214 5214TE LONDON' 'TESCO STORE 6071 6071TE LONDON'
 'TESCO STORES 2288 CLEVEDON' 'TFL ENFORCEMENT OPS WEB LONDON'
 'TFL TRAVEL CH          TFL.GOV.UK/CP GB                           '
 'TFL TRAVEL CH     TFL.GOV.UK/CP' 'TFL TRAVEL CHARGE       TFL.GOV.UK/CP'
 'THAMES WATER' 'THE  WHITE  COMPANY THE UNITED KINGDOM'
 'THE CHAMPIONSHIPS, WIMB WIMBLEDON' 'THE CINNAMON TREE LTD   LONDON'
 'THE CONDE NAST PUBLICAT LONDON'
 'THE GOOD BOOK CO LTD   SURREY        GB                           '
 'THE GOOD BOOK COMPANY L Epsom' 'THE GOOD BOOK COMPANY L London'
 'THE IVY CAFE WIMBLEDON  LONDON' 'THE IVY ON THE SQUARE   EDINBURGH'
 'The Nelson Pharmacy     London' 'THE ROYAL YACHT BRITANN EDINBURGH'
 'THE ROYAL YACHT BRITANN LEITH' 'THE ROYAL YACHT BRITANN LEITH EDINBUR'
 'THE SCOTCH WHISKEY EXPE MIDLOTHIAN'
 'TM *TICKETMASTER        LOS ANGELES' 'TREATWELL               LONDON'
 'UBER TRIP               AMSTERDAM' 'UNIVERSITY OF EXETEXETER'
 'VANGUARD          LONDON' 'VANGUARD ASSET MANA06F02306050101352'
 'VANGUARD ASSET MANA06F02306050101353'
 'VANGUARD ASSET MANA06F02306050101355'
 'VANGUARD ASSET MANA06F02306050101356'
 'Vita Bella             Chelmsford    GB                           '
 'W H SMITH EUROPE TRAVEL BRISTOL' 'WAGAMAMA LIMITED        LONDON'
 'WAITROSE 0767 314N      POTTERS BAR'
 'WAITROSE 846           RAYNES PARK   GB'
 'WAITROSE RAYNES PARK    LONDON' 'WAITROSE WIMBLEDON      LONDON'
 'WEDGEWOOD               EDINBURGH'
 'Westminster Dental     London        GB                           '
 'WESTSIDE TENNIS CLUB    WIMBLEDON' 'WHITE HART HOTEL  EXETER'
 'WIMBLEDON BOOKS LTD     LONDON'
 'Wimbledon Flower Kiosk London        GB                           '
 'WINDMILL TEAROOMS      LONDON        GB                           '
 'WINDMILL TEAROOMS LONDON' 'Window Cleaner    16 Carlton Park Av'
 'WISHLIST                LONDON' 'WISLEY GLASSHOUSE CAFE  SURREY'
 'WM MORRISONS STORES     LONDON' 'WOLDINGHAM GOLF CLWOLDINGHAM CA'
 'WOODHAM MORTIMER GOLF  WOODHAM MORTI GB                           '
 'WORLD OF GOLF LONDON    NEW MALDEN'
 'WWW.ARGOS.CO.UK        MILTON KEYNES GB                           '
 'WWW.GOODEARTHGROUP.CO. LONDON  SW19  GB'
 'WWW.KIDLY.CO.UK        LONDON        GB                           '
 'WWW.PACTCOFFEE.COM      LONDON'
 'WWW.PPRUSSELLSQUARE.CO 02078333005   GB'
 'WWW.RAVECOFFEE.CO.UK   CIRENCESTERC  GB                           '
 'WWW.TAKEAWAY.JE        01534876163   GB'
 'X4139 SPORTS            LONDON'
 'ZETTLE_*CHANGO EMPANAD LONDON        GB                           '
 'Zettle_*PLONK GOLFlondon'
 'ZETTLE_*THE WILDS GROU BARNET        GB                           ']

In [3]:
TransactionDescription=H1Transactions.loc[0,'Description']
Categories=str(H1Transactions['Category'].unique())

In [66]:
# print(TransactionDescription)
print(Categories)

['Other' 'Home' 'Lunch and coffee' 'Presents' 'Savings' 'Financial gift'
 'Baby' 'Entertainment' 'Internal Transfers' 'Expenses' 'Personal Items'
 'Holidays' 'Restaurants and fast food' 'Insurance' 'Mortgage'
 'Food Shopping' 'Medical' 'Mobile/Internet' 'Income' 'Travel'
 'Sports/leisure' 'Nursery' 'Giving' 'Monzo Personal Spend' 'Council Tax'
 'Utilities' 'Books/Magazines/Papers']

In [35]:
prompt = ("Classify the following purchase description into one of the following categories in this list: (Other,Home,Lunch and coffee,Presents,Savings,Financial gift,Baby,Entertainment,Internal Transfers,Expenses,Personal Items,
Holidays,Restaurants and fast food,Insurance,Mortgage,Food Shopping,Medical,Mobile/Internet,Income,Travel,
 'Sports/leisure' 'Nursery' 'Giving' 'Monzo Personal Spend' 'Council Tax'
 'Utilities' 'Books/Magazines/Papers'). The purchase description is" + TransactionDescription)
print(prompt)

['Other' 'Home' 'Lunch and coffee' 'Presents' 'Savings' 'Financial gift'
 'Baby' 'Entertainment' 'Internal Transfers' 'Expenses' 'Personal Items'
 'Holidays' 'Restaurants and fast food' 'Insurance' 'Mortgage'
 'Food Shopping' 'Medical' 'Mobile/Internet' 'Income' 'Travel'
 'Sports/leisure' 'Nursery' 'Giving' 'Monzo Personal Spend' 'Council Tax'
 'Utilities' 'Books/Magazines/Papers']

TypeError: can only concatenate str (not "NoneType") to str

In [48]:
prompt = ("Classify the following purchase description into one of the following categories in this list:"+Categories+" The purchase description is: " + TransactionDescription)
print(prompt)

Classify the following purchase description into one of the following categories in this list:['Other' 'Home' 'Lunch and coffee' 'Presents' 'Savings' 'Financial gift'
 'Baby' 'Entertainment' 'Internal Transfers' 'Expenses' 'Personal Items'
 'Holidays' 'Restaurants and fast food' 'Insurance' 'Mortgage'
 'Food Shopping' 'Medical' 'Mobile/Internet' 'Income' 'Travel'
 'Sports/leisure' 'Nursery' 'Giving' 'Monzo Personal Spend' 'Council Tax'
 'Utilities' 'Books/Magazines/Papers'] The purchase description is: *306-0043263-0976896 M UXBRIDGE

In [40]:
# Make the API request
response = requests.post(endpoint, json=data, headers=headers)

# Check for a successful response and process the output
if response.status_code == 200:
    result = response.json()
    generated_text = result["choices"][0]["text"]
    print(generated_text)
else:
    print(f"Error: {response.status_code} - {response.text}")

coffee

In [49]:
print(prompt)

Classify the following purchase description into one of the following categories in this list:['Other' 'Home' 'Lunch and coffee' 'Presents' 'Savings' 'Financial gift'
 'Baby' 'Entertainment' 'Internal Transfers' 'Expenses' 'Personal Items'
 'Holidays' 'Restaurants and fast food' 'Insurance' 'Mortgage'
 'Food Shopping' 'Medical' 'Mobile/Internet' 'Income' 'Travel'
 'Sports/leisure' 'Nursery' 'Giving' 'Monzo Personal Spend' 'Council Tax'
 'Utilities' 'Books/Magazines/Papers'] The purchase description is: *306-0043263-0976896 M UXBRIDGE

In [59]:
def TransactionDescription(x):
    return H1Transactions.loc[x,'Description']

In [4]:
# Convert a specific column to an ordered list
TransactionDescriptionList= str(H1Transactions['Description'].tolist())

print(TransactionDescriptionList)

['*306-0043263-0976896 M UXBRIDGE', '*306-0043263-0976896 M UXBRIDGE', '*306-0043291-4166692 M UXBRIDGE', '*306-0043919-5058005 M UXBRIDGE', '0100 - COLLIERSWOOD?    COLLIERS WOOD S', '0800 HOMEFIX LTD        YATELEY', '0C385 BOOST             LONDON', '3CC5D                   LONDON', '3CPAYMENT*PRET A MANGER KINGSTON UPON T', '3CPAYMENT*STARBUCKS 127 LONDON', '3CPAYMENT*STARBUCKS 127 LONDON', '3CPAYMENT*STARBUCKS 127 LONDON', '3CPAYMENT*STARBUCKS 287 EDINBURGH', '3CPAYMENT*THE WOOLLEN M EDINBURGH', '3CPAYMENT*WELCOME BREAK HUNGERFORD', '3CPAYMENT*WELCOME BREAK POTTERS BAR', 'Absolute Taste Ltd t/a  Bicester', 'ADAMS J     *FRS  REGULAR SAVER', 'ADAMS J     *FRS  REGULAR SAVER', 'ADAMS J     *FRS  REGULAR SAVER', 'ADAMS J     *FRS  REGULAR SAVER', 'ADAMS J     *FRS  REGULAR SAVER', 'ADAMS J     *FRS  REGULAR SAVER', 'ADAMS NF&N        From Ann For Easte', 'ADAMS NF&N        Happy Anniversary', 'ADAMS NF&N        Happy Birthday', 'ADAMS R     *FRS  REGULAR ROSS', 'ADAMS R     *FRS  REGULAR ROSS', 'ADAMS R     *FRS  REGULAR ROSS', 'ADAMS R     *FRS  REGULAR ROSS', 'ADAMS R     *FRS  REGULAR ROSS', 'ADAMS R     *FRS  REGULAR ROSS', 'ALDI COLLIERS WOOD 7810 COLLIERS WOOD', 'ALDI COLLIERS WOOD 7810 COLLIERS WOOD', 'ALDI COLLIERS WOOD 7810 COLLIERS WOOD', 'ALDI COLLIERS WOOD 7810 COLLIERS WOOD', 'ALDI COLLIERS WOOD 7810 COLLIERS WOOD', 'ALDI COLLIERS WOOD 7810 COLLIERS WOOD', 'ALDI COLLIERS WOOD 7810 COLLIERS WOOD', 'ALDI COLLIERS WOOD 7810 COLLIERS WOOD', 'ALDI COLLIERS WOOD 7810 COLLIERS WOOD', 'AMAZON PRIME*1H35W84U4  AMZN.CO.UK/PM', 'AMAZON PRIME*1Q63I9T84  AMZN.CO.UK/PM', 'AMAZON PRIME*1R11Z9O64  AMZN.CO.UK/PM', 'AMAZON PRIME*9Y70Z0TD5  AMZN.CO.UK/PM', 'AMAZON PRIME*JM1BS6AB5  AMZN.CO.UK/PM', 'AMAZON PRIME*K52KN36R5  AMZN.CO.UK/PM', 'AMAZON PRIME*OY1E04205  AMZN.CO.UK/PM', 'AMAZON PRIME*R68VU5OI5  AMZN.CO.UK/PM', 'AMAZON PRIME*UX0IN94N5  AMZN.CO.UK/PM', 'AMAZON.CO.UK*015J83AB5  AMAZON.CO.UK', 'AMAZON.CO.UK*1A0AH7OW4  AMAZON.CO.UK', 'AMAZON.CO.UK*1X8O02VO4  AMAZON.CO.UK', 'AMAZON.CO.UK*HP1DE5MD5  AMAZON.CO.UK', 'AMAZON.CO.UK*MT01N9865  AMAZON.CO.UK', 'AMAZON.CO.UK*P87NW8EZ5  353-12477661', 'AMERICAN EXPRESS', 'AMERICAN EXPRESS', 'AMERICAN EXPRESS', 'AMERICAN EXPRESS', 'AMERICAN EXPRESS', 'AMERICAN EXPRESS', 'AMZ*BEST LEARNING UK    AMAZON.CO.UK', 'AMZ*BEST LEARNING UK    AMAZON.CO.UK', 'AMZ*PARTY DELIGHTS L SV PAY.AMAZON.CO', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'Angel Hill Site 62Farnborough', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL         08001076285   IE', 'APPLE.COM/BILL         08001076285   IE', 'APPLE.COM/BILL         APPLE.COM/BIL IE                           ', 'APPLE.COM/BILL         APPLE.COM/BIL IE                           ', 'APPLE.COM/BILL         CORK          IE                           ', 'APPLE.COM/BILL         CORK          IE                           ', 'APPLE.COM/UK            HOLLYHILL', 'ARGOS LIMITED           MILTON KEYNES', 'ARGOS LIMITED           MILTON KEYNES', 'ARGOS LIMITED           MILTON KEYNES', 'Atom Easy         Atom Easy', 'AVIOS GROUP Avios Group CRAWLEY', 'B & Q 1076             NEW MALDEN    GB', 'B & Q 1076             NEW MALDEN    GB', 'B & Q 1076        NEW MALDEN', 'B&Q NEW MALDEN 1076     NEW MALDEN', 'Babylon 76-78           London', 'Babylon 76-78           London', 'Babylon 76-78           London', 'Babylon 76-78           London', 'Babylon 76-78           London', 'Babylon 76-78           London', 'Babylon 76-78           London', 'Babylon 76-78           London', 'Babylon 76-78          London        GB', 'Babylon 76-78          London        GB', 'BABYLON 76-78          LONDON  SW20  GB', 'BABYLON 76-78          LONDON  SW20  GB', 'Babylon 76-78     London', 'BARCLAYS INSURANCE', 'BARCLAYS INSURANCE', 'BARCLAYS INSURANCE', 'BARCLAYS INSURANCE', 'BARCLAYS INSURANCE', 'BARCLAYS INSURANCE', 'BARCLAYS UK MTGES', 'BARCLAYS UK MTGES', 'BARCLAYS UK MTGES', 'BARCLAYS UK MTGES', 'BARCLAYS UK MTGES', 'BARCLAYS UK MTGES', 'Bayley and Sage   London', 'Bayley Wimbledon       London        GB                           ', 'Bayley Wimbledon       London        GB                           ', 'Bayley Wimbledon       London        GB                           ', 'Bayley Wimbledon  London', 'BB-TRAVEL INSURANC     GREAT DUNMOW  GB                           ', "BLACKWELL'S EXETEREXETER", 'Booking.com             Amsterdam', 'BOOTS                   BRISTOL', 'BOOTS                   BRISTOL', 'BOOTS                   NOTTINGHAM', 'BOOTS                   NOTTINGHAM', 'BOOTS 0853             WIMBLEDON     GB', 'BOOTS 0853             WIMBLEDON     GB', 'BOOTS 1000        LONDON', 'BOOTS OPTICIANS         LONDON', 'BOOTS REWARDSCHEME', 'BOOTS REWARDSCHEME', 'BOOTS REWARDSCHEME', 'BOOTS REWARDSCHEME', 'BOOTS REWARDSCHEME', 'BOOTS REWARDSCHEME', 'BOOTS THE CHEMIST       LONDON', 'BOOTS THE CHEMIST       LONDON', 'BOOTS THE CHEMIST       LONDON', 'BOOTS THE CHEMIST       LONDON', 'BOOTS THE CHEMIST       LONDON', 'BOOTS THE CHEMIST       LONDON', 'BOOTS THE CHEMIST       LONDON', 'BOOTS THE CHEMIST       LONDON', 'BOOTS THE CHEMIST       LONDON', 'BOOTS THE CHEMIST       LONDON', 'BOOTS THE CHEMIST       LONDON', 'BRISTOL AIRPORT SSP SAC BRISTOL', 'BRITISH AIRWAYS GB DIRE WEST DRAYTON', 'BRITISH AIRWAYS GB DIRE WEST DRAYTON', 'BT GROUP PLC', 'BT GROUP PLC', 'BT GROUP PLC', 'BT GROUP PLC', 'BT GROUP PLC', 'BT GROUP PLC', 'C1CA4 SPORTS            LONDON', 'CABVISION NETWORK LONDON', 'CASH 0000    APR03SOUTH WEST T@13.53', 'CASH 0000    JAN05SOUTH WEST T@11.44', 'CASH 0000    JUN26SOUTH WEST T@09.48', 'CASH Card    MAY05COOPERATIVE @16.05', 'CASH Card    MAY07COOPERATIVE @12.22', 'CASH Card    MAY09COOPERATIVE @09.57', 'CHARLOTTE TILBURY BTY   LONDON', 'Chegworth Valley       Harrietsham   GB                           ', 'CHQ  IN AT 400704', 'CIRCOLO POPOLARE        LONDON', 'CITY PANTRY             LONDON', 'CLEVEDON SF CONNECT     AVON', 'CMCT CHURCH EVENTS      LONDON', 'CMCT CHURCH EVENTS      LONDON', 'CMCT CHURCH EVENTS      LONDON', 'CO-MISSION EVENTS       LONDON', 'CO-MISSION EVENTS       LONDON', 'CO-MISSION EVENTS       LONDON', 'CO-OP GROUP 070789SHOREDITCH (S', 'CO-OP OLD STREET        LONDON', 'CO-OP RAYNES PARK       LONDON', 'CO-OP RAYNES PARK       LONDON', 'COSTA EDINBURGH AIRPORT EDINBURGH', 'DART-CHARGE            LEEDS         GB                           ', 'DAVID LLOYD            LONDON        GB                           ', 'DAVID LLOYD            LONDON        GB                           ', 'DAVID LLOYD LEISUR', 'DAVID LLOYD LEISUR', 'DAVID LLOYD LEISUR', 'DAVID LLOYD LEISUR', 'DAVID LLOYD LEISUR', 'DAVID LLOYD LEISUR', 'DAVID LLOYD LEISUR', 'David Lloyd Leisure Li Hatfield      GB                           ', 'David Lloyd Leisure Li Hatfield      GB                           ', 'David Lloyd Leisure Li Hatfield      GB                           ', 'David Lloyd Leisure Li Hatfield      GB                           ', 'David Lloyd Leisure Li Hatfield      GB                           ', 'David Lloyd Leisure Li Hatfield      GB                           ', 'David Lloyd Leisure Li Hatfield      GB                           ', 'David Lloyd Leisure Li Hatfield      GB                           ', 'David Lloyd Leisure Li Hatfield      GB                           ', 'DAVID LLOYD LEISURE LIM HATFIELD', 'DAVID LLOYD LEISURE LIM HATFIELD', 'DAVID LLOYD LEISURE LIM HATFIELD', 'David Lloyd Raynes Park London', 'DELIVEROO               LONDON', 'DELIVEROO               LONDON', 'DELIVEROO               LONDON', 'DELIVEROO               LONDON', 'Dicky Birds       510066', 'Dicky Birds       510066', 'Dicky Birds       510066', 'Dicky Birds       510066', 'Dicky Birds       510066', 'Dicky Birds       RORY  ADAMS', 'DISHOOM EDINBURGH       EDINBURGH', 'DMN* PLONKGOLF-SHOREDI  COLCHESTER', 'DMN* PLONKGOLF-SHOREDI  COLCHESTER', 'DUNDONALD CHURCH  ADAMS', 'DUNDONALD CHURCH  ADAMS', 'DUNDONALD CHURCH  ADAMS', 'DUNDONALD CHURCH  ADAMS', 'DUNDONALD CHURCH  ADAMS', 'DUNDONALD CHURCH  ADAMS', 'EA5C9 BOOST             LONDON', 'EASYJET*EASYJET K4Q1CRP LUTON', 'EASYJET*EASYJET K5B5WRS LUTON', 'EDINBURGH TRAMS LIMITE EDINBURGH     GB                           ', 'EE LIMITED', 'EE LIMITED', 'EE LIMITED', 'EE LIMITED', 'EE LIMITED        FIRST PAYMENT', 'ELYS                   LONDON        GB                           ', 'ELYS                   LONDON        GB                           ', 'ELYS                   LONDON        GB                           ', 'ELYS (WIMBLEDON) PLC    LONDON', 'ELYS (WIMBLEDON) PLC    LONDON', 'ELYS (WIMBLEDON) PLC    LONDON', 'ELYS (WIMBLEDON) PLC    LONDON', 'ELYS (WIMBLEDON) PLC    LONDON', 'ELYS (WIMBLEDON) PLC    LONDON', 'EMMA BRIDGEWATER LTD    LONDON', 'EPOSNOW*RASCALS SOFTPLA NORWICH', 'EPOSNOW*RASCALS SOFTPLA NORWICH', 'EPOSNOW*RASCALS SOFTPLA NORWICH', 'EPOSNOW*RASCALS SOFTPLA NORWICH', 'EPOSNOW*RASCALS SOFTPLA NORWICH', 'EPOSNOW*RASCALS SOFTPLA NORWICH', 'EPOSNOW*RASCALS SOFTPLA NORWICH', 'ESSO HOGS BACK SSTSURREY', 'EXETER UNI PRINT REXETER', 'F9DDD SPORTS            LONDON', 'FACULTY SCIENCE LIFACULTY SCIENC PAY', 'FACULTY SCIENCE LIFACULTY SCIENC PAY', 'FACULTY SCIENCE LIFACULTY SCIENC PAY', 'FACULTY SCIENCE LIFACULTY SCIENC PAY', 'FACULTY SCIENCE LIFACULTY SCIENC PAY', 'FACULTY SCIENCE LIFACULTY SCIENC PAY', 'FACULTY SCIENCE LTNO REF', 'FAMLY             FIRST PAYMENT', 'FE3FC BOOST             LONDON', 'FINGAL                  LEITH EDINBUR', 'FIRST DIRECT VISA', 'FIRST DIRECT VISA', 'FIRST DIRECT VISA', 'FIRST DIRECT VISA', 'FIRST DIRECT VISA FIRST PAYMENT', 'FIRST DIRECT VISA FIRST PAYMENT', 'FRANCO MANCA      LONDON', 'Funding Circle UK', 'Funding Circle UK', 'Funding Circle UK', 'GOLFNOW                 BELFAST', 'GOODWOOD ESTATE COMPANY CHICHESTER', 'Headmasters Wimbledon V London', 'HM.COM                  LONDON', 'HMRC SA', 'HMRC SA', 'HOLLAND AND BARRETT     NUNEATON', 'HOME RETAIL GROUP PLC   CENTRAL MILTON', 'HOME RETAIL GROUP PLC   CENTRAL MILTON', 'HOME RETAIL GROUP PLC   CENTRAL MILTON', 'HOME RETAIL GROUP PLC   CENTRAL MILTON', 'HOMEOFFICE/PAYROLL', 'HOMEOFFICE/PAYROLL', 'HOMEOFFICE/PAYROLL', 'HOMEOFFICE/PAYROLL', 'HOMEOFFICE/PAYROLL', 'HOMEOFFICE/PAYROLL', 'IKEA LTD SHOP ONLINE   LONDON        GB                           ', 'JG *MACMILLAN CANCER S  LONDON', 'JOHN LEWIS DIRECT       LONDON', 'JOHN LEWIS DIRECT       LONDON', 'JOHN LEWIS DIRECT       LONDON', 'JOHN LEWIS DIRECT       LONDON', 'JOHN LEWIS DIRECT       LONDON', 'JOHN LEWIS DIRECT       LONDON', 'JOHN LEWIS DIRECT       LONDON', 'JOHN LEWIS DIRECT       LONDON', 'JOHN LEWIS DIRECT       LONDON', 'JOHN LEWIS KINGSTON     KINGSTON UPON T', 'JOHN LEWIS KINGSTON     KINGSTON UPON T', 'JOJO MAMAN BEBE LTD-WIM WIMBLEDON', 'JOJO MAMAN BEBE LTD-WIM WIMBLEDON', 'JOJO MAMAN BEBE LTD-WIM WIMBLEDON', 'JOJO_ECOM_UK            NEWPORT', 'Julia Adams       Money', 'Julia Adams       Money', 'Julia Adams       Playhouse', 'Julia Adams       Playhouse', 'JULIA MONZO       JULIA MONZO', 'JULIA MONZO       JULIA MONZO', 'JULIA MONZO       JULIA MONZO', 'JULIA MONZO       JULIA MONZO', 'JULIA MONZO       JULIA MONZO', 'JULIA MONZO       JULIA MONZO', 'JULIA MONZO       JULIA MONZO', 'JUST PARKING LTD       LONDON        GB                           ', 'KENT PARKWOOD           CANTERBURY', 'KENT PARKWOOD           CANTERBURY', 'LA REDOUTE             BRADFORD WEST GB                           ', 'LAITHWAITES-RECURRING L READING', 'LAKELAND.LIMITED       WINDERMERE    GB                           ', 'LARK                    LONDON', 'LARK                    LONDON', 'LARK                    LONDON', 'LARK                    LONDON', 'LARK                    LONDON', 'LARK                    LONDON', 'LARK                   LONDON  SW20  GB', 'LB MERTON', 'LB MERTON', 'LB MERTON', 'LB MERTON', 'LB MERTON - RINGO PARK BASINGSTOKE   GB                           ', 'LB MERTON - RINGO PARK BASINGSTOKE   GB                           ', 'LB MERTON - RINGO PARK BASINGSTOKE   GB                           ', 'LB MERTON - RINGO PARK BASINGSTOKE   GB                           ', 'LIMPOPO BILTONG        MILTON KEYNES GB                           ', 'LOLA COFFEE             EDINBURGH', 'LONDON BOROUGH OF      MERTON        GB                           ', 'LONDORA NAIL BOUTIQUE  WIMBLEDON     GB                           ', 'LTA Operations LimLondon', 'LTA Operations LimLondon', 'LUCAS CAR WASH LTD      LONDON', 'M&S COLLIERS WOOD       LONDON', 'M&S WIMBLEDON           LONDON', 'M&S WIMBLEDON           LONDON', 'M&S WIMBLEDON           LONDON', 'M&S WIMBLEDON           LONDON', 'M&S WIMBLEDON           LONDON', 'M&S WIMBLEDON           LONDON', 'M&S WIMBLEDON           LONDON', 'MARKS&SPENCER PLC SACA LONDON EC1V   GB', 'MARKS&SPENCER PLC SACA LONDON EC1V   GB', 'MCDONALDS              WESTERHAM     GB                           ', 'MEDIPHARMACY           LONON         GB                           ', 'MILO S                 LONDON        GB                           ', 'MOBILE REBORN LTD 70-01-01-5496', 'Mum & Dad         NHM', 'NEXT ONLINE NEXT APPLEP UNITED KINGDOM', 'NEXT ONLINE NEXT APPLEP UNITED KINGDOM', 'NEXT ONLINE NEXT APPLEP UNITED KINGDOM', 'NO11                    EDINBURGH', 'NYX*LRS                NewMalden     GB                           ', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'PAUL RAJKUMAR     DONATION', 'PAUL RAJKUMAR     DONATION', 'PAUL RAJKUMAR     DONATION', 'PAUL RAJKUMAR     DONATION', 'PAUL RAJKUMAR     DONATION', 'PAUL RAJKUMAR     DONATION', 'PAY* HANDY.COM-APR13   LONDON        GB', 'PAY* HANDY.COM-APR13   LONDON        GB', 'PAY* HANDY.COM-JUN26   LONDON        GB', 'PAY* HANDY.COM-MAY03   LONDON        GB', 'PAY* HANDY.COM-MAY29   LONDON        GB', 'PAYMENT RECEIVED - THANK YOU', 'PAYMENT RECEIVED - THANK YOU', 'PAYMENT RECEIVED - THANK YOU', 'PAYMENT RECEIVED - THANK YOU', 'PAYMENT RECEIVED - THANK YOU', 'PAYMENT RECEIVED - THANK YOU', 'PAYMENT RECEIVED - THANK YOU                                      ', 'PAYMENT RECEIVED - THANK YOU                                      ', 'PAYMENT RECEIVED - THANK YOU                                      ', 'PAYPAL *BMWORLDWIDE     01912705143', 'PAYPAL *BODEN           4029357733', 'PAYPAL *BQLIMITED       03330143357', 'PAYPAL *CUTTERSQUID     02084530212', 'PAYPAL *CUTTERSQUID     02084530212', 'PAYPAL *MD UK           660494296', 'PAYPAL *MD UK           660494296', 'PAYPAL *SCREWFIX        03330112112', 'PAYPAL *SCREWFIX        03330112112', 'PAYPAL *SCREWFIX        03330112112', 'PAYPAL *SCREWFIX        03330112112', 'PAYPAL *TRG PLC         02031175455', 'PAYPAL *XMASDIRECT      01350727555', 'PENNYHILL PARK SPABAGSHOT', 'PHL & ELLAS KITCHEN     NEWTOWN', 'Portland Scallop Compa Portland      GB                           ', 'Portland Scallop Compa Portland      GB                           ', 'Portland Scallop Compan Portland', 'POST OFFICE RAYNES PARK LONDON', 'POSTMARK                LONDON', 'POSTMARK                LONDON', 'POSTMARK TRADING LTD   LONDON        GB                           ', 'PRIME VIDEO *135OX6ZY4  353-12477661', 'PRIME VIDEO *1O2VJ4UM4  353-12477661', 'Provenance Village But London        GB                           ', 'Provenance Village But London        GB                           ', 'Provenance Village But London        GB                           ', 'PROVENANCE VILLAGE BUTC LONDON', 'Provenance VillageLondon', 'Raynes Park ExpresLondon', 'Raynes Park Express     London', 'Raynes Park Express    London        GB                           ', 'Rebecca Spence    Happy Birthday', 'RINGGO PARKING    MAIDSTONE', 'ROBERT AND EDWARDS     LONDON  SW19  GB', 'ROBERT AND EDWARDS LTD  LONDON', 'Ross Adams        IOU', 'Ross Adams        IOU', 'Ross Adams        IOU', 'ROSS ADAMS        MONZO', 'Ross Adams        NowTV', 'Ross Adams        NowTV', 'Ross Adams        Transfer', 'ROSS MONZO 2      MONZO TOP UP', 'ROSS MONZO 2      MONZO TOP UP', 'ROSS MONZO 2      MONZO TOP UP', 'ROSS MONZO 2      MONZO TOP UP', 'ROSS MONZO 2      MONZO TOP UP', 'ROSS MONZO 2      MONZO TOP UP', "SAINSBURY'S LOCAL CLEVE CLEVEDON", "SAINSBURY'S LOCAL CLEVE CLEVEDON", "SAINSBURY'S LOCAL WESMI LONDON", "SAINSBURY'S SPRMRKTS LT LONDON", "SAINSBURY'S SUPERMARKET LONDON", "SAINSBURY'S SUPERMARKET LONDON", "SAINSBURY'S SUPERMARKET LONDON", "SAINSBURY'S SUPERMARKET LONDON", "SAINSBURY'S SUPERMARKET LONDON", "SAINSBURY'S SUPERMARKET LONDON", "SAINSBURY'S SUPERMARKET LONDON", "SAINSBURY'S SUPERMARKET LONDON", "SAINSBURY'S SUPERMARKET LONDON", "SAINSBURY'S SUPERMARKET LONDON", 'SAINSBURYS             RAYNES PARK   GB                           ', 'Sarah Crabtree    Picnic', 'SEPHORA UK              ST PETER', 'SHELL ENERGY', 'SHELL ENERGY', 'SHELL ENERGY', 'SHELL ENERGY', 'SHELL ENERGY', 'SHELL ENERGY', 'SHELL PEPYS 427        LONDON SW20   GB', 'SHELTER NAT CAMP', 'SHELTER NAT CAMP', 'SHELTER NAT CAMP', 'SHELTER NAT CAMP', 'SHELTER NAT CAMP', 'SHELTER NAT CAMP  FIRST PAYMENT', 'SP BABY MORI LIMITED    LONDON', 'SP FRENCH CONNECTION    LONDON', 'SP NEIGHBOURHOOD COF   LIVERPOOL     GB                           ', 'SP OMAZE UK             ALTRINCHAM', 'SP OMAZE UK             ALTRINCHAM', 'SPAR                   LONDON        GB                           ', 'SPOTIFY           LONDON', 'SPOTIFY           LONDON', 'SPOTIFY           LONDON', 'SPOTIFY           LONDON', 'SPOTIFY           LONDON', 'SPOTIFY           LONDON', 'SQ *AVIATOR HOTEL Farnborough', 'SQ *FABULOUS COFFEE &  Whitstable    GB                           ', 'SQ *FORTITUDE COFFEE   Edinburgh     GB                           ', 'SQ *THE GREAT BIG EVEN Guildford     GB                           ', 'SQ *THE GREAT BIG EVEN Guildford     GB                           ', 'SQ *WIMBLEDON VILLAGE  London        GB                           ', 'STARBUCKS              LONDON        GB                           ', 'STARBUCKS BRS           BRISTOL', 'SUMUP  *V & G ICE CREA SUTTON        GB                           ', 'SUMUP*DUNDONALD CHURCH  LONDON', 'SUMUP*DUNDONALD CHURCH  LONDON', 'SUMUP*DUNDONALD CHURCH  LONDON', 'SUMUP*DUNDONALD CHURCH  LONDON', 'SUMUP*DUNDONALD CHURCH  LONDON', 'SUMUP*DUNDONALD CHURCH  LONDON', 'SUMUP*DUNDONALD CHURCH  LONDON', 'T Archdale        Golf', 'Tamesis Dock           London        GB                           ', 'TESCO PAY AT PUMP NEW MALDEN', 'TESCO PETROL 3883 3883T NEW MALDEN', 'TESCO PFS 3883    NEW MALDEN', 'TESCO PFS 3883    NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO STORE 2934 2934TE NEW MALDEN', 'TESCO S

In [61]:
print(TransactionDescription(25))

ADAMS NF&N        Happy Birthday

In [120]:

# openai.organization = "org-0aeOV8xLMdS6EktEfObsesQ9"
# openai.api_key = os.getenv("OPENAI_API_KEY")

import requests

# Define your API key and endpoint
api_key = openai.api_key
endpoint = "https://api.openai.com/v1/completions"  # Use the appropriate endpoint for your API call

# Define your prompt or input text

# Set up the headers with your API key
headers = {
    "Authorization": f"Bearer {openai.api_key}",
    "Content-Type": "application/json",
}
Chunk=16
TransactionDescriptionList= str(H1Transactions['Description'].tolist()[(Chunk-1)*50:Chunk*50])
Categories=str(H1Transactions['Category'].unique())
# prompt = "Classify the following purchase description into one of the following categories in this list:(lunch, coffee, clothes, baby). The purchase descriptionis:('3CPAYMENT*STARBUCKS 127)"
prompt = ("I will provide you an ordered list of transaction descriptions. I would like you to return a list of values as a string to populate a new column in my table called Category, with an ordered list of Categories in the same order as the original list.  Classify the following purchase descriptions into one of the following categories in this list:"+Categories+" The purchase descriptions is: " + TransactionDescriptionList)
# Define the data for your API request
data = {
    "model": "gpt-3.5-turbo-instruct",
    "prompt": prompt,
    "max_tokens": 1500,
    "temperature": 0
}

# Make the API request
response = requests.post(endpoint, json=data, headers=headers)

# Check for a successful response and process the output
if response.status_code == 200:
    result = response.json()
    generated_text = result["choices"][0]["text"]
    print(generated_text)
else:
    print(f"Error: {response.status_code} - {response.text}")

['Presents', 'Presents', 'Presents', 'Lunch and coffee', 'Lunch and coffee', 'Food Shopping', 'Sports/leisure', 'Sports/leisure', 'Sports/leisure', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Restaurants and fast food', 'Entertainment', 'Restaurants and fast food', 'Entertainment', 'Entertainment']

In [39]:
print(TransactionDescriptionList)

['AMAZON.CO.UK*015J83AB5  AMAZON.CO.UK', 'AMAZON.CO.UK*1A0AH7OW4  AMAZON.CO.UK', 'AMAZON.CO.UK*1X8O02VO4  AMAZON.CO.UK', 'AMAZON.CO.UK*HP1DE5MD5  AMAZON.CO.UK', 'AMAZON.CO.UK*MT01N9865  AMAZON.CO.UK', 'AMAZON.CO.UK*P87NW8EZ5  353-12477661', 'AMERICAN EXPRESS', 'AMERICAN EXPRESS', 'AMERICAN EXPRESS', 'AMERICAN EXPRESS', 'AMERICAN EXPRESS', 'AMERICAN EXPRESS', 'AMZ*BEST LEARNING UK    AMAZON.CO.UK', 'AMZ*BEST LEARNING UK    AMAZON.CO.UK', 'AMZ*PARTY DELIGHTS L SV PAY.AMAZON.CO', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'AMZNMKTPLACE            AMAZON.CO.UK', 'Angel Hill Site 62Farnborough', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL          HOLLYHILL', 'APPLE.COM/BILL         08001076285   IE', 'APPLE.COM/BILL         08001076285   IE', 'APPLE.COM/BILL         APPLE.COM/BIL IE                           ', 'APPLE.COM/BILL         APPLE.COM/BIL IE                           ', 'APPLE.COM/BILL         CORK          IE                           ', 'APPLE.COM/BILL         CORK          IE                           ']

In [121]:
NewCategory=generated_text.split(',')
print(len(NewCategory))
# print(NewCategory)
# # df['Split_Values'] = df['Values'].str.split(',')
# # Apply the function to create the new column
# H1Transactions['New_Category'] = H1Transactions.apply(NewCategory,axis=1)

# Save the updated DataFrame back to a CSV file
# H1Transactions.to_csv('/Users/rossadams/Documents/Finances/ExportedCSVs/FinH12023CSV/updated_Transactions-H1-Transactions.csv', index=False)
# This code will read the existing CSV file, add a new column based on your custom function, and save the updated data to a new CSV file.

# Apply the function to create the new column
# H1Transactions['NewCategory'] = H1Transactions['Category'].apply(NewCategory)

# # Save the updated DataFrame back to a CSV file
# H1Transactions.to_csv('/Users/rossadams/Documents/Finances/ExportedCSVs/FinH12023CSV/updated_Transactions-H1-Transactions.csv', index=False)

33

In [122]:
for i in range(len(NewCategory)):
    NewCategory[i] = NewCategory[i].replace('\n\n', '')
print(NewCategory)
print(len(NewCategory))

["['Presents'", " 'Presents'", " 'Presents'", " 'Lunch and coffee'", " 'Lunch and coffee'", " 'Food Shopping'", " 'Sports/leisure'", " 'Sports/leisure'", " 'Sports/leisure'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Restaurants and fast food'", " 'Entertainment'", " 'Restaurants and fast food'", " 'Entertainment'", " 'Entertainment']"]
33

In [126]:
H1Transactions.loc[(Chunk-1)*50:Chunk*50-18, 'NewCategory'] = NewCategory

H1Transactions.to_csv('/Users/rossadams/Documents/Finances/ExportedCSVs/FinH12023CSV/updated_Transactions-H1-Transactions.csv', index=False)

In [34]:
H1Transactions.head()

,Date,Description,Unnamed: 2,Amount,Net,Unnamed: 5,Category,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,NewCategory
0,18/02/2023,*306-0043263-0976896 M UXBRIDGE,MRS J ADAMS,37.5,-37.5,NaN,Other,RFI CHARGEBACK CLERK\nMARKS AND SPENCER\nALEXA...,SALFORD,M50 3SP,UNITED KINGDOM OF GB AND NI,AT230490044000011820418,General Purchases-Department Stores,['Other'
1,28/02/2023,*306-0043263-0976896 M UXBRIDGE,MRS J ADAMS,-22.5,22.5,NaN,Other,RFI CHARGEBACK CLERK\nMARKS AND SPENCER\nALEXA...,SALFORD,M50 3SP,UNITED KINGDOM OF GB AND NI,AT230600045000011947084,General Purchases-Department Stores,'Other'
2,20/02/2023,*306-0043291-4166692 M UXBRIDGE,MRS J ADAMS,22.5,-22.5,NaN,Other,RFI CHARGEBACK CLERK\nMARKS AND SPENCER\nALEXA...,SALFORD,M50 3SP,UNITED KINGDOM OF GB AND NI,AT230520048000011666062,General Purchases-Department Stores,'Other'
3,30/03/2023,*306-0043919-5058005 M UXBRIDGE,MRS J ADAMS,7.0,-7.0,NaN,Other,RFI CHARGEBACK CLERK\nMARKS AND SPENCER\nALEXA...,SALFORD,M50 3SP,UNITED KINGDOM OF GB AND NI,AT230890038000011934194,General Purchases-Department Stores,'Other'
4,18/04/2023,0100 - COLLIERSWOOD? COLLIERS WOOD S,MRS J ADAMS,16.0,-16.0,NaN,Other,UNIT 1\nTANDEM CENTRE,COLLIERSWOOD,GU,UNITED KINGDOM OF GB AND NI,AT231090028000011841574,General Purchases-Furnishing,'Restaurants and fast food'

In [51]:
print(NewCategory[0:49])

["['Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'", " 'Other'"]